/**
 * Medical content seed (spec §17 "Medical Content System",
 * §31 "Seed/dummy data matching frontend content").
 *
 * IMPORTANT - review status
 * -------------------------
 * These entries are authored drafts. They are seeded in `clinical_review`
 * status, NOT `approved`, because the spec requires a named reviewer to sign
 * off before content can be served (§17: "AI retrieves approved content";
 * §31: "Clinical content is sourced, reviewed and versioned").
 *
 * Nothing here is served to users until a reviewer approves it through
 * POST /api/v1/content/admin/:contentId/status. For local development you can
 * set SEED_CONTENT_AUTO_APPROVE=true to approve the seed automatically; that
 * flag is refused in production.
 *
 * Deliberately NOT seeded: the item wording for EPDS, PHQ-9 and GAD-7.
 * Validated instruments must use their licensed wording, which has to be loaded
 * from the licence holder rather than paraphrased. Until it is loaded, the
 * screening endpoints report `itemsAvailable: false` rather than presenting an
 * approximation.
 */

const REVIEW_DUE = '2026-08-14';

function pregnancyWeek(week, title, body) {
  return {
    contentId: `mc_pregnancy_week_${String(week).padStart(2, '0')}`,
    title,
    body,
    lifeStages: ['pregnancy'],
    topics: ['pregnancy', 'milestones'],
    audience: 'female_user',
    contentType: 'article',
    readingTimeMinutes: 2,
    source: 'NICE NG201 antenatal care; WHO recommendations on antenatal care for a positive pregnancy experience',
    reviewDueDate: REVIEW_DUE,
  };
}

function postpartumDay(day, title, body, topics = ['postpartum', 'recovery']) {
  return {
    contentId: `mc_postpartum_day_${String(day).padStart(2, '0')}`,
    title,
    body,
    lifeStages: ['postpartum'],
    topics,
    audience: 'female_user',
    contentType: 'article',
    readingTimeMinutes: 2,
    source: 'WHO recommendations on maternal and newborn care for a positive postnatal experience; NICE NG194',
    reviewDueDate: REVIEW_DUE,
  };
}

export const MEDICAL_CONTENT_SEED = [
  /* ---------------- Pregnancy milestones ---------------- */
  pregnancyWeek(4, 'Pregnancy confirmed',
    'A home pregnancy test detects hCG, which usually becomes measurable around the time a period is due. A positive test is a good moment to contact a provider so antenatal care can be arranged. Dating is confirmed later by ultrasound, so the week shown here may shift.'),
  pregnancyWeek(6, 'Booking appointment window',
    'Most services aim to see you for a booking appointment before 10 weeks. This visit covers your medical history, screening choices, and any medicines you take. It is worth writing down questions in advance.'),
  pregnancyWeek(8, 'Early pregnancy changes',
    'Nausea, tiredness, tender breasts and changes in appetite are common in the first trimester and vary widely between people. Small, frequent meals and rest help some people. Persistent vomiting that stops you keeping fluids down needs medical assessment.'),
  pregnancyWeek(12, 'End of the first trimester',
    'Around this point many services offer first-trimester screening and a dating scan. Early pregnancy symptoms often ease over the following weeks, though this is not true for everyone.'),
  pregnancyWeek(16, 'Second trimester',
    'Energy often improves in the second trimester. Some people begin to feel movement between 16 and 24 weeks, and first pregnancies commonly notice it later.'),
  pregnancyWeek(20, 'Anatomy scan window',
    'The mid-pregnancy scan checks the development of the baby and the position of the placenta. It is usually offered between 18 and 21 weeks.'),
  pregnancyWeek(24, 'Glucose screening window',
    'Screening for gestational diabetes is commonly offered between 24 and 28 weeks, earlier if you have risk factors. From around this point, monitoring your baby’s pattern of movements becomes important.'),
  pregnancyWeek(28, 'Third trimester',
    'Appointments usually become more frequent from here. Blood pressure and growth are monitored, and anti-D is offered if you are RhD negative.'),
  pregnancyWeek(32, 'Growth check window',
    'Growth and position are commonly checked around this point. Many people start thinking about birth preferences now.'),
  pregnancyWeek(36, 'Preparing for birth',
    'Your provider will discuss the baby’s position and your birth plan. It is a good time to prepare practical things and to know who to call, and when.'),
  pregnancyWeek(37, 'Full term',
    'From 37 weeks a pregnancy is considered term. Labour beginning any time from now is within the normal range.'),
  pregnancyWeek(40, 'Due date',
    'A due date is an estimate, not a deadline. Most births happen in the weeks around it. Your provider will discuss monitoring and options if the pregnancy continues past term.'),

  /* ---------------- Postpartum ---------------- */
  postpartumDay(1, 'The first days',
    'The first days are about rest, feeding and recovery. Bleeding, cramping and soreness are expected. Know the warning signs that need urgent attention and keep your provider’s number to hand.'),
  postpartumDay(7, 'First week',
    'Bleeding usually begins to reduce over the first week. Pain that is increasing rather than easing, a fever, or a wound that becomes hot and painful should be assessed.'),
  postpartumDay(14, 'Two week wellbeing check-in',
    'Mood changes in the first two weeks are common. If low mood, anxiety or a sense of detachment persists beyond two weeks, or if it is interfering with daily life, it is worth talking to a health professional. Support is effective and widely available.',
    ['postpartum', 'mental_health']),
  postpartumDay(42, 'Six week postnatal review',
    'Around six weeks most services offer a postnatal review covering physical recovery, mood, contraception and any ongoing symptoms. Raise anything that has been bothering you, including pelvic floor symptoms and pain during sex.',
    ['postpartum', 'appointment']),
  postpartumDay(90, 'Three month check-in',
    'Recovery continues well past six weeks. Persistent pelvic floor symptoms, back pain, or low mood are common reasons to seek further support rather than signs of failure.',
    ['postpartum', 'mental_health']),
  postpartumDay(180, 'Six month check-in',
    'Sleep, mood and physical recovery often shift again around this point. If something has not settled, it is reasonable to ask for a referral.',
    ['postpartum', 'mental_health']),
  postpartumDay(365, 'One year',
    'The postnatal period is often described as a full year. Ongoing symptoms deserve attention at any point in it.'),

  /* ---------------- Red flag articles ---------------- */
  {
    contentId: 'mc_pregnancy_redflag_bleeding',
    title: 'Bleeding during pregnancy',
    body: 'Any vaginal bleeding during pregnancy should be assessed promptly. Causes range from harmless to serious, and only an examination can tell them apart. Contact your maternity unit or emergency services rather than waiting for your next appointment.',
    lifeStages: ['pregnancy'], topics: ['red_flag', 'pregnancy'], audience: 'female_user', contentType: 'safety',
    source: 'NICE NG121 ectopic pregnancy and miscarriage; RCOG guidance', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_pregnancy_redflag_preeclampsia',
    title: 'Severe headache, vision changes and swelling',
    body: 'A severe headache, sudden vision changes, upper abdominal pain, or rapid swelling of the face and hands after 20 weeks can indicate pre-eclampsia, which needs same-day assessment. Blood pressure and urine testing are the first checks.',
    lifeStages: ['pregnancy'], topics: ['red_flag', 'pregnancy'], audience: 'female_user', contentType: 'safety',
    source: 'NICE NG133 hypertension in pregnancy', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_pregnancy_redflag_movements',
    title: 'Changes in your baby’s movements',
    body: 'There is no set number of movements to expect. What matters is a change from your baby’s own pattern. If movements reduce or feel different, contact your maternity unit the same day. Do not wait, and do not rely on eating or drinking something cold to prompt movement.',
    lifeStages: ['pregnancy'], topics: ['red_flag', 'pregnancy'], audience: 'female_user', contentType: 'safety',
    source: 'RCOG Green-top Guideline No. 57 reduced fetal movements', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_pregnancy_redflag_abdominal_pain',
    title: 'Severe abdominal pain in pregnancy',
    body: 'Severe, constant or worsening abdominal pain in pregnancy needs urgent assessment, particularly with bleeding, a hard abdomen, or feeling unwell.',
    lifeStages: ['pregnancy'], topics: ['red_flag', 'pregnancy'], audience: 'female_user', contentType: 'safety',
    source: 'NICE NG121; RCOG guidance', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_pregnancy_redflag_fluid',
    title: 'Fluid leaking in pregnancy',
    body: 'A gush or steady trickle of fluid may mean your waters have broken. Contact your maternity unit the same day so it can be confirmed and your care planned, especially before 37 weeks.',
    lifeStages: ['pregnancy'], topics: ['red_flag', 'pregnancy'], audience: 'female_user', contentType: 'safety',
    source: 'NICE NG121; NICE NG25 preterm labour and birth', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_perinatal_redflag_fever',
    title: 'Fever during pregnancy or after birth',
    body: 'A temperature above 38C during pregnancy or in the weeks after birth should be assessed the same day. Infection can progress quickly in this period.',
    lifeStages: ['pregnancy', 'postpartum'], topics: ['red_flag'], audience: 'female_user', contentType: 'safety',
    source: 'WHO postnatal care recommendations; RCOG sepsis guidance', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_postpartum_redflag_haemorrhage',
    title: 'Heavy bleeding after birth',
    body: 'Soaking a maternity pad in under an hour, passing clots larger than a golf ball, or feeling faint needs emergency assessment. Postpartum haemorrhage can occur in the days and weeks after birth, not only immediately.',
    lifeStages: ['postpartum'], topics: ['red_flag', 'postpartum'], audience: 'female_user', contentType: 'safety',
    source: 'WHO postnatal care recommendations; RCOG Green-top Guideline No. 52', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_perinatal_redflag_vte',
    title: 'Signs of a blood clot',
    body: 'Pregnancy and the weeks after birth raise the risk of blood clots. Pain, swelling or redness in one calf, chest pain, coughing blood, or sudden breathlessness need emergency assessment.',
    lifeStages: ['pregnancy', 'postpartum'], topics: ['red_flag'], audience: 'female_user', contentType: 'safety',
    source: 'RCOG Green-top Guideline No. 37b', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_mentalhealth_crisis',
    title: 'If you are having thoughts of harming yourself',
    body: 'These thoughts are more common than most people realise and they can be treated. Contact your local emergency number or a crisis line now, or tell someone you trust and stay with them. If you can, move away from anything you could use to hurt yourself.',
    lifeStages: [], topics: ['red_flag', 'mental_health'], audience: 'female_user', contentType: 'safety',
    source: 'WHO mhGAP intervention guide', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_postpartum_crisis',
    title: 'Frightening thoughts after birth',
    body: 'Intrusive, frightening thoughts about harm are reported by many new parents and are usually a symptom of anxiety rather than an intention. They are treatable. Tell a health professional today, and stay with someone you trust.',
    lifeStages: ['postpartum'], topics: ['red_flag', 'mental_health'], audience: 'female_user', contentType: 'safety',
    source: 'WHO mhGAP intervention guide; NICE CG192 antenatal and postnatal mental health', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_gyn_redflag_pelvic_pain',
    title: 'Severe pelvic pain',
    body: 'Pain severe enough to stop you working, sleeping or moving normally should be assessed. Persistent severe period pain is not something to simply endure, and can point to conditions such as endometriosis that benefit from diagnosis.',
    lifeStages: ['cycle_tracking', 'hormonal_health', 'ttc', 'perimenopause', 'everyday_wellness', 'first_period'],
    topics: ['red_flag', 'pain'], audience: 'female_user', contentType: 'safety',
    source: 'NICE NG73 endometriosis diagnosis and management', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_menopause_redflag_bleeding',
    title: 'Bleeding after menopause',
    body: 'Any vaginal bleeding twelve months or more after your last period should always be checked by a clinician, even if it is light or happens once. Most causes are not cancer, but it needs to be excluded promptly.',
    lifeStages: ['menopause'], topics: ['red_flag', 'menopause'], audience: 'female_user', contentType: 'safety',
    source: 'NICE NG12 suspected cancer recognition and referral', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_gyn_redflag_heavy_bleeding',
    title: 'Heavy or prolonged bleeding',
    body: 'Bleeding that soaks through protection hourly, lasts longer than seven days, or interferes with daily life is worth reviewing with a clinician. Treatments exist, and persistent heavy bleeding can cause anaemia.',
    lifeStages: ['cycle_tracking', 'hormonal_health', 'ttc', 'perimenopause', 'first_period', 'everyday_wellness'],
    topics: ['red_flag', 'bleeding'], audience: 'female_user', contentType: 'safety',
    source: 'NICE NG88 heavy menstrual bleeding', reviewDueDate: REVIEW_DUE,
  },

  /* ---------------- Care plan linked content ---------------- */
  {
    contentId: 'mc_comfort_period_pain',
    title: 'Comfort options for period pain',
    body: 'Heat applied to the lower abdomen, gentle movement, and over-the-counter anti-inflammatory pain relief taken as directed are the first-line options most people find helpful. If pain regularly stops you functioning, or is not controlled by these, it is worth a clinical review rather than a higher dose.',
    lifeStages: ['cycle_tracking', 'hormonal_health', 'first_period', 'perimenopause'],
    topics: ['comfort', 'pain'], audience: 'female_user', contentType: 'article', readingTimeMinutes: 3,
    source: 'NICE CKS dysmenorrhoea; NICE NG88', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_postpartum_screening_intro',
    title: 'About the wellbeing check-in',
    body: 'This is a short questionnaire used widely in postnatal care to help identify people who might benefit from more support. It is a screening tool, not a diagnosis: only a clinician can diagnose. Your answers stay private unless you choose to share them.',
    lifeStages: ['postpartum'], topics: ['mental_health', 'screening'], audience: 'female_user', contentType: 'article',
    readingTimeMinutes: 1, source: 'NICE CG192 antenatal and postnatal mental health', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_menopause_bone_heart',
    title: 'Bone and heart health after menopause',
    body: 'The fall in oestrogen after menopause affects bone density and cardiovascular risk. Weight-bearing and resistance exercise, adequate calcium and vitamin D, not smoking, and blood pressure and cholesterol checks are the measures with the strongest evidence. Whether HRT is appropriate is an individual decision to make with a clinician.',
    lifeStages: ['menopause', 'perimenopause'], topics: ['preventive_care', 'menopause'], audience: 'female_user',
    contentType: 'article', readingTimeMinutes: 4,
    source: 'NICE NG23 menopause diagnosis and management', reviewDueDate: REVIEW_DUE,
  },

  /* ---------------- Partner Learn (spec §13) ---------------- */
  {
    contentId: 'mc_partner_understand_cycle',
    title: 'Understanding the menstrual cycle',
    body: 'The cycle is usually described in phases, but experience varies enormously between people and between cycles. Rather than predicting how she feels from a phase, ask. The most useful thing you can know is her own pattern, and only if she chooses to share it.',
    lifeStages: [], topics: ['understand_her_body'], audience: 'partner', contentType: 'article', readingTimeMinutes: 3,
    source: 'General reproductive health education', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_partner_understand_emotions',
    title: 'Understanding her emotions',
    body: 'Attributing someone’s feelings to hormones is one of the fastest ways to make them feel dismissed. Emotions in any life stage have context: work, sleep, pain, relationships. Ask what is going on, listen without solving, and take what she says at face value.',
    lifeStages: [], topics: ['understand_her_emotions'], audience: 'partner', contentType: 'article', readingTimeMinutes: 3,
    source: 'General relational health education', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_partner_be_better_support',
    title: 'Being better at supporting',
    body: 'Practical support is often what helps most: taking a task off her list without being asked, protecting her rest, or simply being present. Ask which of these would help today rather than assuming, and accept the answer if it is "space".',
    lifeStages: [], topics: ['be_better_at_supporting'], audience: 'partner', contentType: 'article', readingTimeMinutes: 3,
    source: 'General relational health education', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_partner_pregnancy_support',
    title: 'Supporting through pregnancy',
    body: 'Attend appointments if you can, learn the warning signs that need urgent care, and take on more of the practical load as pregnancy progresses. If she reports a symptom that worries her, help her get it checked rather than reassuring her out of it.',
    lifeStages: ['pregnancy'], topics: ['understand_her_body', 'be_better_at_supporting'], audience: 'partner',
    contentType: 'article', readingTimeMinutes: 3, source: 'NICE NG201 antenatal care', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_partner_postpartum_support',
    title: 'Supporting after birth',
    body: 'Recovery from birth takes months, not weeks. Protect her sleep where you can, take on night-time tasks that do not require her, and watch for persistent low mood, anxiety or withdrawal beyond the first two weeks. Encourage professional support early; it works.',
    lifeStages: ['postpartum'], topics: ['be_better_at_supporting', 'mental_health'], audience: 'partner',
    contentType: 'article', readingTimeMinutes: 3, source: 'NICE CG192; WHO postnatal care recommendations', reviewDueDate: REVIEW_DUE,
  },

  /* ---------------- First period ---------------- */
  {
    contentId: 'mc_firstperiod_preparation',
    title: 'Getting ready for your first period',
    body: 'Most first periods happen between ages 10 and 15, usually a couple of years after breasts start developing. It helps to keep a small kit in your bag: pads or period underwear, spare underwear, and a note of who you can ask for help at school. Early periods are often irregular for the first year or two, and that is normal.',
    lifeStages: ['first_period'], topics: ['education', 'puberty'], audience: 'female_user', contentType: 'article',
    readingTimeMinutes: 3, source: 'General adolescent health education', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_firstperiod_school_sports',
    title: 'Periods at school and in sport',
    body: 'You can do everything you normally do during a period, including swimming and sport. Pack what you need, know where supplies are kept at school, and tell a teacher you trust if you need help. Pain that stops you taking part is worth talking to an adult and a clinician about.',
    lifeStages: ['first_period'], topics: ['education', 'puberty'], audience: 'female_user', contentType: 'article',
    readingTimeMinutes: 2, source: 'General adolescent health education', reviewDueDate: REVIEW_DUE,
  },

  /* ---------------- Hormonal health ---------------- */
  {
    contentId: 'mc_hormonal_pcos_overview',
    title: 'PCOS: what it is and is not',
    body: 'Polycystic ovary syndrome is diagnosed clinically, usually using a combination of irregular ovulation, signs of raised androgens, and ultrasound findings. It cannot be diagnosed from an app. If you have been diagnosed, tracking symptoms over time gives your clinician a much clearer picture than memory alone.',
    lifeStages: ['hormonal_health'], topics: ['conditions', 'pcos'], audience: 'female_user', contentType: 'article',
    readingTimeMinutes: 4, source: 'International evidence-based guideline for the assessment and management of PCOS (2023)', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_hormonal_endometriosis_overview',
    title: 'Endometriosis: recognising the pattern',
    body: 'Endometriosis commonly causes period pain that does not respond to usual pain relief, pain during or after sex, pain opening bowels or passing urine, and fatigue. Diagnosis is often delayed, so a clear symptom record helps. Treatment options exist at every level of severity.',
    lifeStages: ['hormonal_health'], topics: ['conditions', 'endometriosis'], audience: 'female_user',
    contentType: 'article', readingTimeMinutes: 4, source: 'NICE NG73 endometriosis', reviewDueDate: REVIEW_DUE,
  },

  /* ---------------- Perimenopause / menopause ---------------- */
  {
    contentId: 'mc_perimenopause_overview',
    title: 'What perimenopause can feel like',
    body: 'Perimenopause is the stretch of years when cycles become less predictable before periods stop. Reported experiences include changes in cycle length and flow, hot flushes, disturbed sleep, mood changes and joint aches. There is no test that reliably stages it, so what you notice over time is the most useful evidence.',
    lifeStages: ['perimenopause'], topics: ['menopause', 'education'], audience: 'female_user', contentType: 'article',
    readingTimeMinutes: 4, source: 'NICE NG23 menopause diagnosis and management', reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: 'mc_menopause_hrt_education',
    title: 'Understanding treatment options',
    body: 'Options for menopausal symptoms include hormone therapy, non-hormonal medicines, and behavioural approaches such as CBT for hot flushes and sleep. Benefits and risks differ by age, time since menopause, personal and family history, and the type and route of treatment. This is a conversation to have with a clinician; Blushy does not recommend or prescribe.',
    lifeStages: ['menopause', 'perimenopause'], topics: ['menopause', 'treatment'], audience: 'female_user',
    contentType: 'article', readingTimeMinutes: 5, source: 'NICE NG23 menopause diagnosis and management', reviewDueDate: REVIEW_DUE,
  },

  /* ---------------- Everyday wellness ---------------- */
  {
    contentId: 'mc_wellness_sleep_basics',
    title: 'Sleep that actually helps',
    body: 'Consistent wake times, daylight early in the day, and a wind-down that does not involve a screen are the changes with the most evidence behind them. If you are regularly sleeping badly for over a month, that is worth raising with a clinician rather than optimising alone.',
    lifeStages: ['everyday_wellness', 'cycle_tracking', 'perimenopause', 'menopause'], topics: ['sleep', 'wellness'],
    audience: 'female_user', contentType: 'article', readingTimeMinutes: 3,
    source: 'General sleep health education; NICE CKS insomnia', reviewDueDate: REVIEW_DUE,
  },
];


/**
 * Partner Learn library (spec §13 "Partner Learn: Understand Her Body;
 * Understand Her Emotions; Be Better at Supporting").
 *
 * Ported from copy that previously lived hardcoded in the Partner Learn
 * screen, where it carried no source, reviewer or version and so could not
 * satisfy §31. The wording is unchanged; what is new is that it now has
 * provenance and has to pass clinical review before it is served.
 *
 * `source` says plainly that this is app-authored education awaiting review.
 * No external guideline is cited, because none was cited originally and
 * inventing one would be worse than stating the truth.
 *
 * Life stage tags are deliberately sparse: the original screen carried stage
 * via enclosing conditionals that could not be recovered reliably, and a
 * mis-tagged article would be shown confidently to the wrong person. A
 * reviewer sets the final tags.
 */
export const PARTNER_LEARN_SEED = [
  {
    contentId: "mc_partner_understanding_pregnancy_fatigue",
    title: "Understanding Pregnancy Fatigue",
    summary: "Why carrying a pregnancy demands immense cardiovascular rest.",
    body: "Progesterone surges rapidly to support fetal development, causing significant physical tiredness. Her body is working constantly to build a new life.\n\nWhat helps: Encourage daytime naps, keep the house quiet, and help with heavy chores.",
    lifeStages: ["pregnancy"],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_nutrition_fluid_hydration_in_pregnancy",
    title: "Nutrition & Fluid Hydration in Pregnancy",
    summary: "Supporting blood volume expansion and fetal nutrition.",
    body: "Blood volume expands by nearly 50% during pregnancy. Regular hydration and nutrient-dense snacks prevent dizziness and fatigue.\n\nWhat helps: Keep fresh water and healthy snacks readily available throughout the house.",
    lifeStages: ["pregnancy"],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_postural_comfort_lower_back_relief",
    title: "Postural Comfort & Lower Back Relief",
    summary: "Relieving physical strain as center of gravity shifts.",
    body: "Relaxin hormone loosens ligaments, putting pressure on lower back joints and pelvis.\n\nWhat helps: Offer a foot rub or gently place supportive pillows behind her back when resting.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_navigating_period_energy_reset",
    title: "Navigating Period Energy Reset",
    summary: "Why low estrogen and progesterone trigger biological fatigue.",
    body: "During the menstrual phase, progesterone and estrogen levels hit their lowest points. This is a natural biological reset. $partnerName needs quiet rest and lighter physical demands.\n\nWhat helps: Take over practical chores (dishes, meal prep) so $partnerName can rest guilt-free.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_relieving_physical_cramps_muscle_tension",
    title: "Relieving Physical Cramps & Muscle Tension",
    summary: "How uterine contractions cause pelvic discomfort.",
    body: "Prostaglandins trigger muscular contractions that can radiate to the lower back. Heat therapy and gentle warmth relax pelvic muscles.\n\nWhat helps: Brew a warm chamomile tea and prepare a hot water bottle or heating pack.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_restorative_sleep_warmth",
    title: "Restorative Sleep & Warmth",
    summary: "Optimizing room temperature for period recovery.",
    body: "Core body temperature drops slightly during bleeding. Warm blankets and early bedtimes support deep regenerative REM sleep.\n\nWhat helps: Ensure the bedroom is warm and peaceful for an early, restful bedtime.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_the_estrogen_energy_surge",
    title: "The Estrogen Energy Surge",
    summary: "Why rising estrogen boosts stamina, focus, and social drive.",
    body: "As estrogen climbs, mental sharpness and physical stamina rise rapidly. $partnerName will likely feel energetic, creative, and motivated.\n\nWhat helps: Suggest active dates, outdoor walks, or tackling new creative projects together.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_high_metabolic_workout_windows",
    title: "High-Metabolic Workout Windows",
    summary: "Capitalizing on optimal muscle recovery and stamina.",
    body: "Rising estrogen improves insulin sensitivity and muscle recovery. It is the best window of the month for high-energy exercise.\n\nWhat helps: Join $partnerName for a workout, run, or energetic weekend activity.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_social_receptivity_communication",
    title: "Social Receptivity & Communication",
    summary: "Why communication feels effortless during mid-follicular days.",
    body: "Dopamine and serotonin rise alongside estrogen, enhancing social openness and optimistic outlooks.\n\nWhat helps: Plan dinner with friends or engage in inspiring, forward-looking conversations.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_peak_estrogen_vitality_window",
    title: "Peak Estrogen & Vitality Window",
    summary: "Understanding the biological high-point of the cycle.",
    body: "Estrogen hits its monthly peak alongside LH surge, boosting confidence, communication, and natural intimacy drive.\n\nWhat helps: Plan a special date night or express authentic appreciation for her.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_ovulation_discomfort_hydration",
    title: "Ovulation Discomfort & Hydration",
    summary: "Mild pelvic twinges and basal body temperature shifts.",
    body: "Some experience mild ovulation discomfort (mittelschmerz) or sudden energy dips right after peak estrogen. Staying hydrated is key.\n\nWhat helps: Keep fresh water handy and ask gently how her body feels today.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_optimizing_peak_focus_hours",
    title: "Optimizing Peak Focus Hours",
    summary: "Making the most of high verbal fluency and confidence.",
    body: "Verbal recall and executive focus reach their monthly maximum, equipping $partnerName for key decisions.\n\nWhat helps: Encourage her goals and offer positive, uplifting validation.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_progesterone_natural_slowdown",
    title: "Progesterone & Natural Slowdown",
    summary: "Why rising progesterone increases thermal heat and fatigue.",
    body: "Progesterone promotes quiet inward focus and increases body temperature by 0.5°C. $partnerName may tire more easily in the late afternoon.\n\nWhat helps: Keep evenings relaxed and minimize late-night social commitments.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_premenstrual_cravings_metabolism",
    title: "Premenstrual Cravings & Metabolism",
    summary: "Why the body burns 100-300 extra calories per day.",
    body: "Metabolic rate increases in the luteal phase. Craving complex carbs, dark chocolate, and magnesium-rich foods is biologically driven.\n\nWhat helps: Keep healthy snacks, dark chocolate, and magnesium-rich foods available.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_sensory_ease_decompression",
    title: "Sensory Ease & Decompression",
    summary: "Lowering noise and stress during premenstrual days.",
    body: "Serotonin receptivity dips right before bleeding, making loud environments or chaotic schedules feel overwhelming.\n\nWhat helps: Create a peaceful home atmosphere and offer quiet downtime.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_navigating_period_energy_shifts",
    title: "Navigating Period Energy Shifts",
    summary: "Why hormone drops trigger natural fatigue cycles.",
    body: "During the menstrual phase, progesterone and estrogen levels hit their lowest points. This is a natural biological reset. $partnerName may need more quiet time, lighter exercise, and extra sleep.\n\nWhat helps: Take care of practical chores so $partnerName can rest without feeling guilty.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_understanding_physical_energy_waves",
    title: "Understanding Physical Energy Waves",
    summary: "Matching activities with high and low energy days.",
    body: "Estrogen surges increase stamina in earlier cycle weeks, while progesterone rises later promote rest. Paying attention to these patterns makes planning joint activities much easier.\n\nWhat helps: Plan high-energy dates during week 2 and relaxing quiet evenings during week 4.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_supporting_luteal_follicular_recovery",
    title: "Supporting Luteal & Follicular Recovery",
    summary: "How rest and nutrition balance metabolic demands during cycle shifts.",
    body: "Metabolic rates increase slightly during the luteal phase while energy lowers. Providing nutrient-rich meals, hydration, and restful evenings supports physical recovery.\n\nWhat helps: Prepare warm, nourishing meals and encourage restorative evening downtime.",
    lifeStages: [],
    topics: ["understand_her_body"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_managing_low_emotional_bandwidth",
    title: "Managing Low Emotional Bandwidth",
    summary: "Why physical fatigue reduces emotional patience.",
    body: "Physical exhaustion depletes emotional reserves. What feels manageable when rested can feel overwhelming when tired.\n\nWhat helps: Avoid bringing up complex or heavy discussions when $partnerName is physically drained.",
    lifeStages: [],
    topics: ["understand_her_emotions"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_the_power_of_quiet_validation",
    title: "The Power of Quiet Validation",
    summary: "Listening without attempting immediate problem-solving.",
    body: "When tired, $partnerName doesn't need solutions—she needs to feel heard and supported without pressure to perform.\n\nWhat helps: Listen attentively and say: 'Rest up, I'm taking care of everything tonight.'",
    lifeStages: [],
    topics: ["understand_her_emotions"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_de_escalating_decision_fatigue",
    title: "De-escalating Decision Fatigue",
    summary: "Lightening mental load during exhaustion.",
    body: "Decision fatigue compounds physical weariness. Simple choices like 'what's for dinner?' become stressful.\n\nWhat helps: Make low-stakes decisions proactively instead of asking open questions.",
    lifeStages: [],
    topics: ["understand_her_emotions"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_soothing_premenstrual_stress_anxiety",
    title: "Soothing Premenstrual Stress & Anxiety",
    summary: "How GABA receptor shifts increase stress sensitivity.",
    body: "Hormonal shifts alter GABA receptors in the brain, lowering the threshold for stress and overthinking.\n\nWhat helps: Offer a warm hug, brew soothing herbal tea, and reduce household noise.",
    lifeStages: [],
    topics: ["understand_her_emotions"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_emotional_receptivity_grounding",
    title: "Emotional Receptivity & Grounding",
    summary: "Providing a calm anchor during emotional waves.",
    body: "Anxiety feels like a storm inside. A steady, calm partner provides an external nervous system anchor.\n\nWhat helps: Stay calm, use a quiet voice, and reassure $partnerName of your steady presence.",
    lifeStages: [],
    topics: ["understand_her_emotions"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_de_escalating_mental_overwhelm",
    title: "De-escalating Mental Overwhelm",
    summary: "Breaking big challenges into single quiet steps.",
    body: "Overwhelm occurs when too many demands compete for attention simultaneously.\n\nWhat helps: Help break tasks down or take a task off her plate immediately.",
    lifeStages: [],
    topics: ["understand_her_emotions"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_nurturing_shared_joy_connection",
    title: "Nurturing Shared Joy & Connection",
    summary: "Capitalizing on positive emotional harmony.",
    body: "When mood is bright, positive interactions create long-lasting relationship deposits and emotional intimacy.\n\nWhat helps: Share a fun experience, laugh together, or try a new activity.",
    lifeStages: [],
    topics: ["understand_her_emotions"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_deepening_mutual_trust_openness",
    title: "Deepening Mutual Trust & Openness",
    summary: "Expressing gratitude and authentic appreciation.",
    body: "Positive emotional states offer the ideal window for open, loving conversations about future goals and dreams.\n\nWhat helps: Tell $partnerName specifically what you love and appreciate about her.",
    lifeStages: [],
    topics: ["understand_her_emotions"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_sustaining_emotional_balance",
    title: "Sustaining Emotional Balance",
    summary: "Keeping open communication effortless.",
    body: "Maintaining positive connection habits during good days builds a strong buffer for future high-stress weeks.\n\nWhat helps: Plan your upcoming week together with excitement and balance.",
    lifeStages: [],
    topics: ["understand_her_emotions"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_managing_stress_and_premenstrual_shifts",
    title: "Managing Stress and Premenstrual Shifts",
    summary: "How hormone changes affect emotional bandwidth.",
    body: "Premenstrual hormone shifts lower the threshold for stress. What normally feels manageable might feel overwhelming. It isn't overreacting—it's a change in chemical receptors in the brain.\n\nWhat helps: Listen patiently without offering direct advice unless asked. Validation goes a long way.",
    lifeStages: [],
    topics: ["understand_her_emotions"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_emotional_receptivity_active_listening",
    title: "Emotional Receptivity & Active Listening",
    summary: "Creating a safe space for open emotional sharing without judgment.",
    body: "Active listening means giving full attention without formulating solutions immediately. Acknowledging emotional experience builds closeness and psychological safety.\n\nWhat helps: Say: 'I hear how tough today was for you, and I am right here with you.'",
    lifeStages: [],
    topics: ["understand_her_emotions"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_de_escalating_overwhelm_anxiety",
    title: "De-escalating Overwhelm & Anxiety",
    summary: "Simple ways to offer grounding support during stressful moments.",
    body: "When stress peaks, cognitive processing becomes heavy. Offering steady presence, a quiet room, or a comforting warm drink helps soothe the nervous system.\n\nWhat helps: Offer a gentle hug or brew a cup of tea without asking complex questions.",
    lifeStages: [],
    topics: ["understand_her_emotions"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_comfort_help_or_space",
    title: "Comfort, Help, or Space?",
    summary: "How to check in without adding pressure.",
    body: "When $partnerName is overwhelmed, asking 'what can I do?' forces decision-making, adding stress. Instead, categorize help into three pillars: Comfort (tea, heat pad), Help (laundry, dishes), or Space (quiet rest).\n\nWhat helps: Ask directly: 'Would comfort, practical help, or space support you best right now?'",
    lifeStages: [],
    topics: ["be_better_at_supporting"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_proactive_household_partnership",
    title: "Proactive Household Partnership",
    summary: "Taking initiative on daily logistics to lighten mental load.",
    body: "Mental load encompasses planning meals, tracking errands, and managing home chores. Taking proactive responsibility for specific tasks removes decision fatigue for your partner.\n\nWhat helps: Pick 2 daily household tasks (e.g. dishes and trash) and manage them completely.",
    lifeStages: [],
    topics: ["be_better_at_supporting"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
  {
    contentId: "mc_partner_quality_time_vs_quiet_presence",
    title: "Quality Time vs. Quiet Presence",
    summary: "Understanding when shared activities vs quiet presence is needed.",
    body: "Some days call for engaging outings and deep conversations, while other days require quiet side-by-side presence. Tuning into what is needed deepens mutual bond.\n\nWhat helps: Check in: 'Would you like to do an activity together or just relax side-by-side quietly?'",
    lifeStages: [],
    topics: ["be_better_at_supporting"],
    audience: 'partner',
    contentType: 'article',
    readingTimeMinutes: 1,
    source: 'Blushy partner education, authored in-app and pending clinical review',
    reviewDueDate: REVIEW_DUE,
  },
];

export const SEED_CONTENT_COUNT = MEDICAL_CONTENT_SEED.length + PARTNER_LEARN_SEED.length;
