/**
 * Stage education articles.
 *
 * These were seven hardcoded `learnFeeds` maps inside the dashboard -- 74
 * clinical articles on lung surfactant, linea nigra, sciatic nerve pain,
 * postpartum depression and bone health, written into the widget tree with no
 * reviewer, no review date and no locale.
 *
 * Moved here so they pass the same gate as every other piece of clinical copy:
 * seeded in `clinical_review`, served only once a named reviewer has approved
 * them, and translatable per locale rather than frozen in English.
 */
/**
 * Provenance for this batch.
 *
 * These were written as app copy, not drawn from a cited reference. Saying so
 * is the point: the clinical reviewer who approves them is the one who
 * attaches a real source, and until then nobody is misled about where the
 * text came from.
 */
const SOURCE = 'Blushy editorial copy. Awaiting clinical review and sourcing.';

export const STAGE_EDUCATION_SEED = [
  {
    contentId: "edu_hormonal_health_pcos_insulin_resistance_link",
    title: "PCOS Insulin Resistance Link",
    summary: "How diet tweaks and movement improve insulin signaling and restore menstrual cycle timing.",
    body: "How diet tweaks and movement improve insulin signaling and restore menstrual cycle timing.",
    contentType: 'article',
    lifeStages: ["hormonal_health"],
    topics: ["understanding_pcos"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_hormonal_health_androgen_regulation_basics",
    title: "Androgen Regulation Basics",
    summary: "Slowing hirsutism and acne spikes through natural cortisol regulation.",
    body: "Slowing hirsutism and acne spikes through natural cortisol regulation.",
    contentType: 'article',
    lifeStages: ["hormonal_health"],
    topics: ["understanding_pcos"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_hormonal_health_managing_pelvic_inflammation",
    title: "Managing Pelvic Inflammation",
    summary: "Anti-inflammatory nutrition guides to soothe pelvic cramps and uterine muscle stiffness.",
    body: "Anti-inflammatory nutrition guides to soothe pelvic cramps and uterine muscle stiffness.",
    contentType: 'article',
    lifeStages: ["hormonal_health"],
    topics: ["understanding_endometriosis"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_hormonal_health_adenomyosis_vs_endometriosis",
    title: "Adenomyosis vs Endometriosis",
    summary: "Understanding tissue lining growth differences and symptom triggers.",
    body: "Understanding tissue lining growth differences and symptom triggers.",
    contentType: 'article',
    lifeStages: ["hormonal_health"],
    topics: ["understanding_endometriosis"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_hormonal_health_pmdd_neurotransmitter_shifts",
    title: "PMDD Neurotransmitter Shifts",
    summary: "Why progesterone drop spikes serotonin dips, driving heavy premenstrual dysphoria.",
    body: "Why progesterone drop spikes serotonin dips, driving heavy premenstrual dysphoria.",
    contentType: 'article',
    lifeStages: ["hormonal_health"],
    topics: ["understanding_pmdd"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_hormonal_health_pms_vs_pmdd_indicators",
    title: "PMS vs PMDD Indicators",
    summary: "How tracking helps verify symptoms to present clearly at doctor visits.",
    body: "How tracking helps verify symptoms to present clearly at doctor visits.",
    contentType: 'article',
    lifeStages: ["hormonal_health"],
    topics: ["understanding_pmdd"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_hormonal_health_thyroid_and_menstrual_timings",
    title: "Thyroid and Menstrual Timings",
    summary: "How T3/T4 thyroid hormone variances disrupt follicular growth and delay periods.",
    body: "How T3/T4 thyroid hormone variances disrupt follicular growth and delay periods.",
    contentType: 'article',
    lifeStages: ["hormonal_health"],
    topics: ["understanding_irregular_cycles"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_hormonal_health_skipping_ovulation_weeks",
    title: "Skipping Ovulation Weeks",
    summary: "Why anovulatory cycles happen and what they mean for long-term health.",
    body: "Why anovulatory cycles happen and what they mean for long-term health.",
    contentType: 'article',
    lifeStages: ["hormonal_health"],
    topics: ["understanding_irregular_cycles"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_hormonal_health_the_estrogen_progesterone_balance",
    title: "The Estrogen/Progesterone Balance",
    summary: "A beginner's guide to how your regulatory hormones coordinate your rhythm.",
    body: "A beginner's guide to how your regulatory hormones coordinate your rhythm.",
    contentType: 'article',
    lifeStages: ["hormonal_health"],
    topics: ["hormones_explained"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_hormonal_health_cortisol_the_cycle_hijacker",
    title: "Cortisol: The Cycle Hijacker",
    summary: "How daily chronic stress delays ovulation and extends cycle lengths.",
    body: "How daily chronic stress delays ovulation and extends cycle lengths.",
    contentType: 'article',
    lifeStages: ["hormonal_health"],
    topics: ["hormones_explained"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_ttc_the_lh_surge_explained",
    title: "The LH Surge Explained",
    summary: "How luteinizing hormone signals follicles to release an egg and how to identify surges correctly.",
    body: "How luteinizing hormone signals follicles to release an egg and how to identify surges correctly.",
    contentType: 'article',
    lifeStages: ["ttc"],
    topics: ["understanding_ovulation"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_ttc_anovulatory_cycle_signals",
    title: "Anovulatory Cycle Signals",
    summary: "Identifying cycles without ovulation using temperature and cervical indicators.",
    body: "Identifying cycles without ovulation using temperature and cervical indicators.",
    contentType: 'article',
    lifeStages: ["ttc"],
    topics: ["understanding_ovulation"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_ttc_timing_intercourse_for_conception",
    title: "Timing Intercourse for Conception",
    summary: "Optimizing timing within the 5 days leading up to ovulation and the day of.",
    body: "Optimizing timing within the 5 days leading up to ovulation and the day of.",
    contentType: 'article',
    lifeStages: ["ttc"],
    topics: ["fertile_window"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_ttc_sperm_longevity_in_uterus",
    title: "Sperm Longevity in Uterus",
    summary: "Why eggwhite cervical mucus is vital for keeping sperm active for up to 5 days.",
    body: "Why eggwhite cervical mucus is vital for keeping sperm active for up to 5 days.",
    contentType: 'article',
    lifeStages: ["ttc"],
    topics: ["fertile_window"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_ttc_mitochondria_and_egg_quality",
    title: "Mitochondria and Egg Quality",
    summary: "Nutritional and lifestyle factors that protect cellular division energy levels.",
    body: "Nutritional and lifestyle factors that protect cellular division energy levels.",
    contentType: 'article',
    lifeStages: ["ttc"],
    topics: ["egg_health"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_ttc_coq10_and_oocyte_vitality",
    title: "CoQ10 and Oocyte Vitality",
    summary: "Coenzyme Q10 clinical summaries on oocyte development and cellular health.",
    body: "Coenzyme Q10 clinical summaries on oocyte development and cellular health.",
    contentType: 'article',
    lifeStages: ["ttc"],
    topics: ["egg_health"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_ttc_cortisol_vs_progesterone",
    title: "Cortisol vs Progesterone",
    summary: "How high adrenal stress hormones can delay ovulation or shorten the luteal phase.",
    body: "How high adrenal stress hormones can delay ovulation or shorten the luteal phase.",
    contentType: 'article',
    lifeStages: ["ttc"],
    topics: ["stress_fertility"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_ttc_calming_the_nervous_system",
    title: "Calming the Nervous System",
    summary: "Simple daily mindfulness triggers to keep autonomic nervous signals balanced.",
    body: "Simple daily mindfulness triggers to keep autonomic nervous signals balanced.",
    contentType: 'article',
    lifeStages: ["ttc"],
    topics: ["stress_fertility"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_ttc_the_progesterone_thermal_shift",
    title: "The Progesterone Thermal Shift",
    summary: "Why core body temperature jumps 0.3C - 0.5C immediately after ovulation occurs.",
    body: "Why core body temperature jumps 0.3C - 0.5C immediately after ovulation occurs.",
    contentType: 'article',
    lifeStages: ["ttc"],
    topics: ["understanding_bbt"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_ttc_identifying_implantation_dips",
    title: "Identifying Implantation Dips",
    summary: "Understanding mid-luteal temperature fluctuations without countdown anxiety.",
    body: "Understanding mid-luteal temperature fluctuations without countdown anxiety.",
    contentType: 'article',
    lifeStages: ["ttc"],
    topics: ["understanding_bbt"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_pregnancy_baby_sensory_milestones",
    title: "Baby Sensory Milestones",
    summary: "How inner ear development improves coordination and how a baby reacts to outside speech sounds.",
    body: "How inner ear development improves coordination and how a baby reacts to outside speech sounds.",
    contentType: 'article',
    lifeStages: ["pregnancy"],
    topics: ["baby_development"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_pregnancy_fetal_lung_surfactant",
    title: "Fetal Lung Surfactant",
    summary: "Understanding respiratory tissue growths and surfactant layers preparing for life outside.",
    body: "Understanding respiratory tissue growths and surfactant layers preparing for life outside.",
    contentType: 'article',
    lifeStages: ["pregnancy"],
    topics: ["baby_development"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_pregnancy_second_trimester_skin_changes",
    title: "Second Trimester Skin Changes",
    summary: "Linea nigra and stretch mark facts under pregnancy melanocyte-stimulating hormone rises.",
    body: "Linea nigra and stretch mark facts under pregnancy melanocyte-stimulating hormone rises.",
    contentType: 'article',
    lifeStages: ["pregnancy"],
    topics: ["mother_s_body"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_pregnancy_sciatic_nerve_pain_soothers",
    title: "Sciatic Nerve Pain Soothers",
    summary: "How uterus alignment pressure affects pelvic nerves and quick stretches to relieve shooting leg pain.",
    body: "How uterus alignment pressure affects pelvic nerves and quick stretches to relieve shooting leg pain.",
    contentType: 'article',
    lifeStages: ["pregnancy"],
    topics: ["mother_s_body"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_pregnancy_iron_intake_and_red_blood_cells",
    title: "Iron Intake and Red Blood Cells",
    summary: "Increasing dietary iron to support the expanded vascular system during the second trimester.",
    body: "Increasing dietary iron to support the expanded vascular system during the second trimester.",
    contentType: 'article',
    lifeStages: ["pregnancy"],
    topics: ["nutrition"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_pregnancy_maternal_calcium_reserves",
    title: "Maternal Calcium Reserves",
    summary: "Protecting maternal bone density while facilitating baby's skeletal bone hardening stages.",
    body: "Protecting maternal bone density while facilitating baby's skeletal bone hardening stages.",
    contentType: 'article',
    lifeStages: ["pregnancy"],
    topics: ["nutrition"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_pregnancy_left_side_sleep_positions",
    title: "Left Side Sleep Positions",
    summary: "Why sleeping on your left side optimizes blood flow through the inferior vena cava to the placenta.",
    body: "Why sleeping on your left side optimizes blood flow through the inferior vena cava to the placenta.",
    contentType: 'article',
    lifeStages: ["pregnancy"],
    topics: ["sleep"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_pregnancy_managing_midnight_restlessness",
    title: "Managing Midnight Restlessness",
    summary: "Soothe restless legs through warm baths and magnesium-rich evening protocols.",
    body: "Soothe restless legs through warm baths and magnesium-rich evening protocols.",
    contentType: 'article',
    lifeStages: ["pregnancy"],
    topics: ["sleep"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_pregnancy_understanding_braxton_hicks",
    title: "Understanding Braxton Hicks",
    summary: "How uterus micro-contractions act as practice exercises and how to differentiate them from real labor.",
    body: "How uterus micro-contractions act as practice exercises and how to differentiate them from real labor.",
    contentType: 'article',
    lifeStages: ["pregnancy"],
    topics: ["labour_preparation"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_pregnancy_writing_a_gentle_birth_plan",
    title: "Writing a Gentle Birth Plan",
    summary: "A premium collaborative template detailing options for delivery positions and postpartum settings.",
    body: "A premium collaborative template detailing options for delivery positions and postpartum settings.",
    contentType: 'article',
    lifeStages: ["pregnancy"],
    topics: ["labour_preparation"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_postpartum_healing_the_incision_site",
    title: "Healing the Incision Site",
    summary: "How postpartum skin tissues recover from surgeries or tearing, and hygiene targets to check daily.",
    body: "How postpartum skin tissues recover from surgeries or tearing, and hygiene targets to check daily.",
    contentType: 'article',
    lifeStages: ["postpartum"],
    topics: ["physical_recovery"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_postpartum_lochia_flow_stages_traced",
    title: "Lochia Flow Stages Traced",
    summary: "Differentiating bleeding types from weeks 1 to 6 and recognizing normal color shifts.",
    body: "Differentiating bleeding types from weeks 1 to 6 and recognizing normal color shifts.",
    contentType: 'article',
    lifeStages: ["postpartum"],
    topics: ["physical_recovery"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_postpartum_understanding_the_baby_blues",
    title: "Understanding the Baby Blues",
    summary: "Why hormone drops (estrogen/progesterone) during the first 14 days spike emotional sensitivity.",
    body: "Why hormone drops (estrogen/progesterone) during the first 14 days spike emotional sensitivity.",
    contentType: 'article',
    lifeStages: ["postpartum"],
    topics: ["mental_health"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_postpartum_prioritizing_rest_over_chores",
    title: "Prioritizing Rest Over Chores",
    summary: "Mindset tools to bypass social pressure and prioritize postpartum mental recovery.",
    body: "Mindset tools to bypass social pressure and prioritize postpartum mental recovery.",
    contentType: 'article',
    lifeStages: ["postpartum"],
    topics: ["mental_health"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_postpartum_ppd_indicators_screening",
    title: "PPD Indicators & Screening",
    summary: "Recognizing chronic anxiety, sleep shifts, or bonding challenges early.",
    body: "Recognizing chronic anxiety, sleep shifts, or bonding challenges early.",
    contentType: 'article',
    lifeStages: ["postpartum"],
    topics: ["postpartum_depression"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_postpartum_support_networks_overview",
    title: "Support Networks Overview",
    summary: "Identifying professional counselors and community postpartum resources.",
    body: "Identifying professional counselors and community postpartum resources.",
    contentType: 'article',
    lifeStages: ["postpartum"],
    topics: ["postpartum_depression"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_postpartum_achieving_a_comfortable_latch",
    title: "Achieving a Comfortable Latch",
    summary: "Step-by-step guidance on positions (cradle, football) to prevent sore nipples.",
    body: "Step-by-step guidance on positions (cradle, football) to prevent sore nipples.",
    contentType: 'article',
    lifeStages: ["postpartum"],
    topics: ["breastfeeding"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_postpartum_managing_milk_supply_spikes",
    title: "Managing Milk Supply Spikes",
    summary: "How hydration and regular demand patterns optimize breast milk production.",
    body: "How hydration and regular demand patterns optimize breast milk production.",
    contentType: 'article',
    lifeStages: ["postpartum"],
    topics: ["breastfeeding"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_postpartum_pelvic_floor_restorations",
    title: "Pelvic Floor Restorations",
    summary: "Safe post-birth kegel routines and diaphragmatic breathing steps to stabilize deep core tissues.",
    body: "Safe post-birth kegel routines and diaphragmatic breathing steps to stabilize deep core tissues.",
    contentType: 'article',
    lifeStages: ["postpartum"],
    topics: ["pelvic_floor_recovery"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_postpartum_checking_for_diastasis_recti",
    title: "Checking for Diastasis Recti",
    summary: "How to inspect abdominal separation at week 6 and what movements to avoid.",
    body: "How to inspect abdominal separation at week 6 and what movements to avoid.",
    contentType: 'article',
    lifeStages: ["postpartum"],
    topics: ["pelvic_floor_recovery"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_perimenopause_the_perimenopause_transition",
    title: "The Perimenopause Transition",
    summary: "What happens during the transition phase leading to menopause, and what to expect regarding cycle lengths.",
    body: "What happens during the transition phase leading to menopause, and what to expect regarding cycle lengths.",
    contentType: 'article',
    lifeStages: ["perimenopause"],
    topics: ["understanding_perimenopause"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_perimenopause_recognizing_early_indicators",
    title: "Recognizing Early Indicators",
    summary: "From skipped cycles to minor mood adjustments: identifying the markers early.",
    body: "From skipped cycles to minor mood adjustments: identifying the markers early.",
    contentType: 'article',
    lifeStages: ["perimenopause"],
    topics: ["understanding_perimenopause"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_perimenopause_estrogen_progesterone_fluctuations",
    title: "Estrogen & Progesterone Fluctuations",
    summary: "Why erratic swings in progesterone cause variable cycle spacing and emotional shifts.",
    body: "Why erratic swings in progesterone cause variable cycle spacing and emotional shifts.",
    contentType: 'article',
    lifeStages: ["perimenopause"],
    topics: ["hormonal_changes"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_perimenopause_role_of_fsh_levels",
    title: "Role of FSH Levels",
    summary: "How follicle-stimulating hormones spike as ovaries change their active ovulation responses.",
    body: "How follicle-stimulating hormones spike as ovaries change their active ovulation responses.",
    contentType: 'article',
    lifeStages: ["perimenopause"],
    topics: ["hormonal_changes"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_perimenopause_science_of_vasomotor_symptoms",
    title: "Science of Vasomotor Symptoms",
    summary: "How estrogen drops trick the hypothalamus into triggering cooling flush responses.",
    body: "How estrogen drops trick the hypothalamus into triggering cooling flush responses.",
    contentType: 'article',
    lifeStages: ["perimenopause"],
    topics: ["hot_flashes"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_perimenopause_managing_evening_flares",
    title: "Managing Evening Flares",
    summary: "Lifestyle adjustments, clothing layers, and nutrition tweaks to buffer hot flash triggers.",
    body: "Lifestyle adjustments, clothing layers, and nutrition tweaks to buffer hot flash triggers.",
    contentType: 'article',
    lifeStages: ["perimenopause"],
    topics: ["hot_flashes"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_perimenopause_tackling_sleep_fragmentation",
    title: "Tackling Sleep Fragmentation",
    summary: "Why progesterone drop impairs melatonin release, and tips for deep sleep extensions.",
    body: "Why progesterone drop impairs melatonin release, and tips for deep sleep extensions.",
    contentType: 'article',
    lifeStages: ["perimenopause"],
    topics: ["sleep"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_perimenopause_coping_with_night_sweats",
    title: "Coping with Night Sweats",
    summary: "Optimal fabrics and sleeping hygiene targets to handle midnight temperature spikes.",
    body: "Optimal fabrics and sleeping hygiene targets to handle midnight temperature spikes.",
    contentType: 'article',
    lifeStages: ["perimenopause"],
    topics: ["sleep"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_perimenopause_maintaining_bone_mineral_density",
    title: "Maintaining Bone Mineral Density",
    summary: "Why estrogen drops trigger bone density loss, and the importance of daily calcium targets.",
    body: "Why estrogen drops trigger bone density loss, and the importance of daily calcium targets.",
    contentType: 'article',
    lifeStages: ["perimenopause"],
    topics: ["bone_health"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_perimenopause_strength_training_benefits",
    title: "Strength Training Benefits",
    summary: "How resistance exercises and weights preserve bone structure and joint health.",
    body: "How resistance exercises and weights preserve bone structure and joint health.",
    contentType: 'article',
    lifeStages: ["perimenopause"],
    topics: ["bone_health"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_menopause_life_after_menopause",
    title: "Life After Menopause",
    summary: "Adapting to stable baseline hormone levels and understanding the shifts in post-menopausal vascular parameters.",
    body: "Adapting to stable baseline hormone levels and understanding the shifts in post-menopausal vascular parameters.",
    contentType: 'article',
    lifeStages: ["menopause"],
    topics: ["understanding_menopause"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_menopause_the_post_transition_phase",
    title: "The Post-Transition Phase",
    summary: "Shifting the wellness perspective from cycle trackings to lifelong vitality and muscle health.",
    body: "Shifting the wellness perspective from cycle trackings to lifelong vitality and muscle health.",
    contentType: 'article',
    lifeStages: ["menopause"],
    topics: ["understanding_menopause"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_menopause_preserving_bone_mineral_density",
    title: "Preserving Bone Mineral density",
    summary: "Why estrogen drops trigger osteoblast cell slowdowns, and the role of daily calcium plus Vitamin D.",
    body: "Why estrogen drops trigger osteoblast cell slowdowns, and the role of daily calcium plus Vitamin D.",
    contentType: 'article',
    lifeStages: ["menopause"],
    topics: ["bone_health"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_menopause_resistance_exercises_for_bones",
    title: "Resistance exercises for bones",
    summary: "How load-bearing routines stimulate joint tissues and prevent natural post-menopausal wear.",
    body: "How load-bearing routines stimulate joint tissues and prevent natural post-menopausal wear.",
    contentType: 'article',
    lifeStages: ["menopause"],
    topics: ["bone_health"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_menopause_endothelial_health_after_menopause",
    title: "Endothelial Health after Menopause",
    summary: "Estrogen drop influences blood vessel elasticity. Learn how active walking preserves cardiac tone.",
    body: "Estrogen drop influences blood vessel elasticity. Learn how active walking preserves cardiac tone.",
    contentType: 'article',
    lifeStages: ["menopause"],
    topics: ["heart_health"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_menopause_managing_blood_pressure_baselines",
    title: "Managing blood pressure baselines",
    summary: "Practical habits, hydration routines, and sodium constraints to buffer cardiac spikes.",
    body: "Practical habits, hydration routines, and sodium constraints to buffer cardiac spikes.",
    contentType: 'article',
    lifeStages: ["menopause"],
    topics: ["heart_health"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_menopause_sarcopenia_prevention_guidelines",
    title: "Sarcopenia prevention guidelines",
    summary: "Why post-menopausal bodies require active strength resistances, and simple bands routines.",
    body: "Why post-menopausal bodies require active strength resistances, and simple bands routines.",
    contentType: 'article',
    lifeStages: ["menopause"],
    topics: ["strength_training"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_menopause_joint_safe_strength_movements",
    title: "Joint-safe strength movements",
    summary: "Low-impact modifications for squats, chest presses, and glute bridges to protect cartilage.",
    body: "Low-impact modifications for squats, chest presses, and glute bridges to protect cartilage.",
    contentType: 'article',
    lifeStages: ["menopause"],
    topics: ["strength_training"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_menopause_meeting_daily_protein_targets",
    title: "Meeting daily protein targets",
    summary: "Why post-menopausal users require high protein density (1.2g/kg) to maintain lean tissues.",
    body: "Why post-menopausal users require high protein density (1.2g/kg) to maintain lean tissues.",
    contentType: 'article',
    lifeStages: ["menopause"],
    topics: ["nutrition"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_menopause_calcium_rich_foods_to_include",
    title: "Calcium rich foods to include",
    summary: "Sourcing calcium from leafy greens, fortified milks, almonds, and dairy sources.",
    body: "Sourcing calcium from leafy greens, fortified milks, almonds, and dairy sources.",
    contentType: 'article',
    lifeStages: ["menopause"],
    topics: ["nutrition"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_everyday_wellness_optimal_breakfast_protein",
    title: "Optimal Breakfast Protein",
    summary: "How starting the day with 25-30g protein balances glucose curves and prevents mid-day fatigue spikes.",
    body: "How starting the day with 25-30g protein balances glucose curves and prevents mid-day fatigue spikes.",
    contentType: 'article',
    lifeStages: ["everyday_wellness"],
    topics: ["nutrition"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_everyday_wellness_gut_health_digestion",
    title: "Gut Health & Digestion",
    summary: "Incorporate fermented foods and high fibers to maintain comfortable microbiome balances.",
    body: "Incorporate fermented foods and high fibers to maintain comfortable microbiome balances.",
    contentType: 'article',
    lifeStages: ["everyday_wellness"],
    topics: ["nutrition"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_everyday_wellness_low_impact_strength_routines",
    title: "Low Impact Strength routines",
    summary: "Simple resistance bands and bodyweight sequences to keep core muscle fibers toned safely.",
    body: "Simple resistance bands and bodyweight sequences to keep core muscle fibers toned safely.",
    contentType: 'article',
    lifeStages: ["everyday_wellness"],
    topics: ["exercise"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_everyday_wellness_walking_for_vitality",
    title: "Walking for Vitality",
    summary: "Why brisk daily walks lower vascular risks and keep joint flexibilities steady.",
    body: "Why brisk daily walks lower vascular risks and keep joint flexibilities steady.",
    contentType: 'article',
    lifeStages: ["everyday_wellness"],
    topics: ["exercise"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_everyday_wellness_balancing_daily_schedules",
    title: "Balancing Daily Schedules",
    summary: "How tracking non-reproductive health symptoms (mood, focus, sleep) builds body awareness.",
    body: "How tracking non-reproductive health symptoms (mood, focus, sleep) builds body awareness.",
    contentType: 'article',
    lifeStages: ["everyday_wellness"],
    topics: ["women_s_health"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_everyday_wellness_hormones_lifestyle_baselines",
    title: "Hormones & Lifestyle baselines",
    summary: "Understanding minor endocrine cycles and adjusting exercise patterns accordingly.",
    body: "Understanding minor endocrine cycles and adjusting exercise patterns accordingly.",
    contentType: 'article',
    lifeStages: ["everyday_wellness"],
    topics: ["women_s_health"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_everyday_wellness_diaphragmatic_breathing_guidelines",
    title: "diaphragmatic breathing guidelines",
    summary: "Why 5 minutes of deep nose inhalation triggers vagal nerve relaxations, lowering anxiety.",
    body: "Why 5 minutes of deep nose inhalation triggers vagal nerve relaxations, lowering anxiety.",
    contentType: 'article',
    lifeStages: ["everyday_wellness"],
    topics: ["mental_wellbeing"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_everyday_wellness_gratitude_journaling",
    title: "Gratitude Journaling",
    summary: "Simple daily prompts to anchor positive thoughts and reduce chronic morning stresses.",
    body: "Simple daily prompts to anchor positive thoughts and reduce chronic morning stresses.",
    contentType: 'article',
    lifeStages: ["everyday_wellness"],
    topics: ["mental_wellbeing"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_everyday_wellness_managing_sleep_hygiene",
    title: "Managing Sleep hygiene",
    summary: "Room lighting levels, optimal temperatures, and evening screens setups to optimize deep rest segments.",
    body: "Room lighting levels, optimal temperatures, and evening screens setups to optimize deep rest segments.",
    contentType: 'article',
    lifeStages: ["everyday_wellness"],
    topics: ["sleep"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_everyday_wellness_wind_down_stretching_routines",
    title: "Wind-down Stretching routines",
    summary: "Floor stretches to release physical tensions and facilitate smoother sleep transitions.",
    body: "Floor stretches to release physical tensions and facilitate smoother sleep transitions.",
    contentType: 'article',
    lifeStages: ["everyday_wellness"],
    topics: ["sleep"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_everyday_wellness_lowering_morning_cortisol",
    title: "Lowering Morning Cortisol",
    summary: "Bypassing early phone scrolls to regulate nervous systems and prevent adrenaline spikes.",
    body: "Bypassing early phone scrolls to regulate nervous systems and prevent adrenaline spikes.",
    contentType: 'article',
    lifeStages: ["everyday_wellness"],
    topics: ["stress"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_everyday_wellness_managing_workplace_anxiety",
    title: "Managing workplace anxiety",
    summary: "Mindful breathing pauses and desk alignments to handle work stresses.",
    body: "Mindful breathing pauses and desk alignments to handle work stresses.",
    contentType: 'article',
    lifeStages: ["everyday_wellness"],
    topics: ["stress"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_everyday_wellness_the_pomodoro_focus_focus_method",
    title: "The Pomodoro focus focus method",
    summary: "Structuring 25-minute focus intervals with active walking breaks to maximize mental recovery.",
    body: "Structuring 25-minute focus intervals with active walking breaks to maximize mental recovery.",
    contentType: 'article',
    lifeStages: ["everyday_wellness"],
    topics: ["productivity"],
    audience: 'female_user',
    source: SOURCE,
  },
  {
    contentId: "edu_everyday_wellness_managing_digital_distractions",
    title: "Managing digital distractions",
    summary: "Setting up device notifications filters to protect daily focus blocks.",
    body: "Setting up device notifications filters to protect daily focus blocks.",
    contentType: 'article',
    lifeStages: ["everyday_wellness"],
    topics: ["productivity"],
    audience: 'female_user',
    source: SOURCE,
  },
];

export const STAGE_EDUCATION_COUNT = STAGE_EDUCATION_SEED.length;
