/**
 * menopauseData.js
 * Comprehensive clinical references, health domains, "Teach Me in 30 Seconds",
 * "Life Modes", "Why Am I Seeing This" logic, and treatment registry for Menopause:
 * "Understanding your body. Protecting your health. Living fully."
 */

export const MENOPAUSE_DOMAINS = Object.freeze({
  BONE_MUSCLE: {
    key: 'bone_muscle',
    title: 'Bone & Muscle',
    shortLabel: 'Bone & Muscle',
    icon: 'fitness_center_rounded',
    colorHex: '0xFF0D9488', // Emerald Teal
    bgHex: '0xFFCCFBF1',
    description: 'Protecting bone mineral density and preserving lean muscle mass after estrogen decline.',
    clinicalFocus: 'Resistance training triggers osteoblasts to preserve bone mass; adequate protein combats sarcopenia.',
    screening: 'Consider a baseline DEXA bone density scan starting at age 60–65, or earlier with risk factors.',
  },
  HEART_METABOLIC: {
    key: 'heart_metabolic',
    title: 'Heart & Metabolic',
    shortLabel: 'Heart & Metabolic',
    icon: 'favorite_rounded',
    colorHex: '0xFF2563EB', // Cobalt Blue
    bgHex: '0xFFDBEAFE',
    description: 'Nurturing endothelial elasticity, healthy blood lipids, and stable metabolic energy.',
    clinicalFocus: 'Estrogen cessation alters lipid metabolism; brisk daily walking promotes microvascular health.',
    screening: 'Annual lipid panel (LDL, HDL, triglycerides) and fasting blood glucose / HbA1c review.',
  },
  SLEEP_REST: {
    key: 'sleep_rest',
    title: 'Sleep & Rest',
    shortLabel: 'Sleep & Rest',
    icon: 'nightlight_round',
    colorHex: '0xFF7209B7', // Royal Purple
    bgHex: '0xFFF3E8FF',
    description: 'Stabilizing deep restorative sleep and managing lingering nighttime flushes.',
    clinicalFocus: 'Thermoregulatory threshold shifts can disrupt slow-wave sleep. Evening cooling is restorative.',
    screening: 'Screen for sleep apnea if morning headaches, snoring, or unrefreshing sleep persist.',
  },
  INTIMATE_URINARY: {
    key: 'intimate_urinary',
    title: 'Intimate & Urinary',
    shortLabel: 'Intimate & Urinary',
    icon: 'spa_rounded',
    colorHex: '0xFFF72585', // Vivid Magenta
    bgHex: '0xFFFFE5F0',
    description: 'Sustaining pelvic vitality, vaginal elasticity, and urinary tract comfort (GSM).',
    clinicalFocus: 'Genitourinary Syndrome of Menopause (GSM) is chronic but highly treatable with local moisturizers or therapy.',
    screening: 'Annual pelvic exam and routine checkups. Any postmenopausal bleeding requires prompt ultrasound.',
  },
  MOOD_COGNITION: {
    key: 'mood_cognition',
    title: 'Mood & Cognition',
    shortLabel: 'Mood & Cognition',
    icon: 'psychology_rounded',
    colorHex: '0xFFD97706', // Warm Amber
    bgHex: '0xFFFEF3C7',
    description: 'Supporting emotional equilibrium, cognitive resilience, and mental clarity.',
    clinicalFocus: 'Estrogen receptors are concentrated in the hippocampus and prefrontal cortex; sleep consolidation supports brain fog recovery.',
    screening: 'Discuss unyielding low mood or pervasive anxiety with a primary clinician.',
  },
});

export const TEACH_ME_IN_30_SECONDS = Object.freeze([
  {
    id: 'gsm_explained',
    topic: 'Intimate & Urinary',
    title: 'What is GSM?',
    badge: '30s Read',
    icon: 'spa_rounded',
    colorHex: '0xFFF72585',
    bgHex: '0xFFFFE5F0',
    summary: 'GSM stands for Genitourinary Syndrome of Menopause — changes in vaginal tissue and urinary comfort caused by reduced estrogen.',
    visualCue: 'Lower estrogen thins mucosal lining and reduces moisture, changing pH and elasticity.',
    whatItFeelsLike: 'Dryness, mild friction or burning, discomfort during intimacy, or needing to pee more often.',
    whenToTalkToDoctor: 'If discomfort interferes with daily movement, intimacy, or if you notice any spotting.',
    whatTreatmentsExist: 'Non-hormonal hyaluronic acid moisturizers, silicone lubricants, and localized low-dose vaginal estrogen (creams, pessaries, or rings) which have virtually zero systemic absorption.',
  },
  {
    id: 'bone_density_dexa',
    topic: 'Bone & Muscle',
    title: 'Why Bone Density Matters Now',
    badge: '30s Read',
    icon: 'fitness_center_rounded',
    colorHex: '0xFF0D9488',
    bgHex: '0xFFCCFBF1',
    summary: 'Estrogen slows bone breakdown. After periods end, bone remodeling shifts toward faster breakdown for the first 5 years.',
    visualCue: 'Bones remodel constantly. Resistance and impact exercises act like a signal telling osteoblasts to keep bones dense.',
    whatItFeelsLike: 'Bone loss itself is silent and has no symptoms until a fracture occurs.',
    whenToTalkToDoctor: 'Ask your doctor about a DEXA bone density scan if you are post-menopause or have a family history of osteoporosis.',
    whatTreatmentsExist: 'Strength exercises (weights, resistance bands), 1000–1200mg dietary calcium, Vitamin D3 + K2, and clinical bone therapies if diagnosed with osteopenia/osteoporosis.',
  },
  {
    id: 'heart_health_shift',
    topic: 'Heart & Metabolic',
    title: 'Your Heart in Menopause',
    badge: '30s Read',
    icon: 'favorite_rounded',
    colorHex: '0xFF2563EB',
    bgHex: '0xFFDBEAFE',
    summary: 'Before menopause, estrogen keeps blood vessels flexible and helps maintain higher protective HDL cholesterol.',
    visualCue: 'As natural hormone levels settle, LDL cholesterol can drift upward and blood vessels become slightly stiffer.',
    whatItFeelsLike: 'Gradual shifts in stamina, resting pulse variations, or blood pressure changes.',
    whenToTalkToDoctor: 'Have your blood pressure and fasting cholesterol checked at your routine annual wellness checkup.',
    whatTreatmentsExist: 'Consistent brisk walking, fiber-rich colorful plants, extra virgin olive oil, stress management, and medical therapy when indicated by your doctor.',
  },
  {
    id: 'sleep_thermoregulation',
    topic: 'Sleep & Rest',
    title: 'Why Sleep Disrupts at 3 AM',
    badge: '30s Read',
    icon: 'nightlight_round',
    colorHex: '0xFF7209B7',
    bgHex: '0xFFF3E8FF',
    summary: 'The hypothalamic thermoregulatory center becomes hypersensitive, misinterpreting normal nighttime core temperature shifts.',
    visualCue: 'Around 3 AM, cortisol naturally starts a slow rise while core body temperature fluctuates, easily waking light sleepers.',
    whatItFeelsLike: 'Waking suddenly, feeling warm, heart beating faster, difficulty nodding back off.',
    whenToTalkToDoctor: 'If poor sleep persists more than 3 nights a week for over a month despite sleep hygiene routines.',
    whatTreatmentsExist: 'Drop room temp to 18–19°C, breathable bamboo layers, magnesium glycinate before bed, and discussing MHT or non-hormonal options with your clinician.',
  },
  {
    id: 'mht_window_opportunity',
    topic: 'Medical Care',
    title: 'The Menopause Hormone Therapy Window',
    badge: '30s Read',
    icon: 'medication_rounded',
    colorHex: '0xFFDD0D22',
    bgHex: '0xFFFFECEB',
    summary: 'Modern evidence shows MHT is safest and most effective when initiated within 10 years of menopause onset or before age 60.',
    visualCue: 'Guidelines from the North American Menopause Society (NAMS) emphasize individualized benefit/risk profiles.',
    whatItFeelsLike: 'Relief from hot flashes, night sweats, sleep disruption, and prevention of early bone loss.',
    whenToTalkToDoctor: 'Schedule a dedicated discussion with your gynecologist to review your personal medical history and options.',
    whatTreatmentsExist: 'Body-identical transdermal 17β-estradiol (patches/gels) paired with micronized progesterone (if uterus is present), or non-hormonal prescription alternatives.',
  },
]);

export const LIFE_MODES = Object.freeze({
  NORMAL: {
    key: 'normal',
    label: 'Everyday Life',
    icon: 'spa_rounded',
    colorHex: '0xFF0D9488',
    bgHex: '0xFFCCFBF1',
    description: 'Steady daily balance and holistic health habits.',
  },
  TRAVELLING: {
    key: 'travelling',
    label: 'Travelling',
    icon: 'flight_takeoff_rounded',
    colorHex: '0xFF2563EB',
    bgHex: '0xFFDBEAFE',
    description: 'Focus on hydration, cool cabin layers, timezone sleep management, and medication packing.',
    priorityChips: ['COOL DOWN', 'HYDRATE', 'SLEEP SUPPORT', 'MED REMINDER'],
  },
  EXHAUSTED: {
    key: 'exhausted',
    label: 'Exhausted',
    icon: 'bedtime_rounded',
    colorHex: '0xFF7209B7',
    bgHex: '0xFFF3E8FF',
    description: 'Zero guilt. Protecting energy, low-effort nourishment, and permission to rest.',
    priorityChips: ['DO NOTHING', 'REST', 'EARLY BEDTIME', 'GENTLE STRETCH'],
  },
  BIG_PRESENTATION: {
    key: 'big_presentation',
    label: 'Big Presentation',
    icon: 'work_outline_rounded',
    colorHex: '0xFFD97706',
    bgHex: '0xFFFEF3C7',
    description: 'Cognitive grounding, steady breath pacing, cool layered wardrobe, and calm focus.',
    priorityChips: ['BREATHE', 'COOL LAYERS', 'BRAIN FUEL', 'CONFIDENCE'],
  },
  WEDDING_CELEBRATION: {
    key: 'wedding_celebration',
    label: 'Wedding & Events',
    icon: 'celebration_rounded',
    colorHex: '0xFFF72585',
    bgHex: '0xFFFFE5F0',
    description: 'Enjoying celebrations while pacing hydration and taking quiet rest moments.',
    priorityChips: ['PACE DRINKS', 'COMFORT SHOES', 'HYDRATE', 'ENJOY'],
  },
  EXERCISE_STREAK: {
    key: 'exercise_streak',
    label: 'Exercising More',
    icon: 'directions_run_rounded',
    colorHex: '0xFF0D9488',
    bgHex: '0xFFCCFBF1',
    description: 'Supporting bone strength, muscle recovery, protein intake, and joint warmth.',
    priorityChips: ['PROTEIN', 'JOINT WARMUP', 'STRENGTH', 'REST DAY'],
  },
  BAD_SLEEP_WEEK: {
    key: 'bad_sleep_week',
    label: 'Bad Sleep Week',
    icon: 'hotel_rounded',
    colorHex: '0xFF7209B7',
    bgHex: '0xFFF3E8FF',
    description: 'Compassionate recovery. Avoiding self-blame, gentle sunlight, and quiet evenings.',
    priorityChips: ['DO NOTHING', 'SUNLIGHT', 'NO SCREENS', 'MAGNESIUM'],
  },
  OVERWHELMED: {
    key: 'overwhelmed',
    label: 'Feeling Overwhelmed',
    icon: 'psychology_alt_rounded',
    colorHex: '0xFFFF4A00',
    bgHex: '0xFFFFEBE0',
    description: 'Clearing expectations. Blushy strips down tasks so you can simply breathe.',
    priorityChips: ['DO NOTHING', 'UNPLUG', 'TALK TO DOCSY', 'BREATHE'],
  },
});

export const COMMON_TREATMENTS = Object.freeze([
  {
    id: 'mht_transdermal',
    category: 'Hormone Therapy (MHT)',
    name: 'Transdermal Estradiol Patch',
    commonDose: '25–50 mcg/day twice weekly',
    purpose: 'Vasomotor symptom relief & bone protection',
    safetyNotes: 'Lower risk of thrombosis compared to oral estrogen because it bypasses first-pass liver metabolism.',
  },
  {
    id: 'micronized_progesterone',
    category: 'Hormone Therapy (MHT)',
    name: 'Micronized Progesterone',
    commonDose: '100–200 mg nightly',
    purpose: 'Endometrial protection & promotes restorative sleep',
    safetyNotes: 'Taken nightly by women with a uterus on systemic estrogen.',
  },
  {
    id: 'vaginal_estrogen_cream',
    category: 'Local Intimate Therapy',
    name: 'Vaginal Estradiol Cream / Ring',
    commonDose: 'Local low-dose application 2x weekly',
    purpose: 'Relief of vaginal dryness, burning, and recurrent UTIs',
    safetyNotes: 'Minimal systemic absorption. Highly safe for long-term maintenance of GSM.',
  },
  {
    id: 'hyaluronic_acid_moisturizer',
    category: 'Non-Hormonal Support',
    name: 'Hyaluronic Acid Vaginal Gel',
    commonDose: 'Every 2–3 days as needed',
    purpose: 'Moisture retention & tissue comfort without hormones',
    safetyNotes: 'Over-the-counter non-hormonal biocompatible hydration.',
  },
  {
    id: 'fezolinetant',
    category: 'Prescription Non-Hormonal',
    name: 'Fezolinetant (NK3 Receptor Antagonist)',
    commonDose: '45 mg once daily',
    purpose: 'Blocks brain signals causing hot flashes without hormones',
    safetyNotes: 'Requires baseline liver enzyme blood tests per prescribing guidance.',
  },
  {
    id: 'vitamin_d3_k2',
    category: 'Bone & Metabolic Supplement',
    name: 'Vitamin D3 (2000 IU) + K2',
    commonDose: 'Daily with meal containing healthy fats',
    purpose: 'Calcium absorption and directed mineralization into bone matrix',
    safetyNotes: 'Supports bone mineral retention alongside dietary calcium.',
  },
  {
    id: 'magnesium_glycinate',
    category: 'Sleep & Muscle Supplement',
    name: 'Magnesium Glycinate (200–300 mg)',
    commonDose: '1 hour before bedtime',
    purpose: 'Promotes muscle relaxation and supports calm sleep architecture',
    safetyNotes: 'Gentle on digestion compared to magnesium citrate or oxide.',
  },
]);

export const POSTMENOPAUSAL_BLEEDING_ALERT = Object.freeze({
  isRedFlag: true,
  severity: 'urgent',
  title: 'Postmenopausal Bleeding Notice',
  eyebrow: 'CLINICAL SAFETY CHECK',
  icon: 'emergency_rounded',
  colorHex: '0xFFDD0D22',
  bgHex: '0xFFFFECEB',
  headline: 'Any bleeding or spotting after 12 months without a period requires prompt clinical evaluation.',
  explanation: 'While benign causes (such as vaginal atrophy or cervical polyps) are very common, it is essential to have your gynecologist perform a pelvic examination and pelvic ultrasound to rule out endometrial hyperplasia or other conditions.',
  actions: [
    { label: 'Prepare Doctor Questions', action: 'open_questions' },
    { label: 'Generate Clinician Brief', action: 'open_clinician_brief' },
    { label: 'Learn More', action: 'learn_bleeding' },
  ],
});
