# -*- coding: utf-8 -*-
"""Traces the outer edge of assets/cycle_uterus.png for the cycle tracker.

    python tool/extract_cycle_outline.py

Writes lib/features/home/widgets/cycle_outline.dart: the sticker's outer
outline as a list of points in image space (0..1 on each axis), starting at
the top and running clockwise, plus the image's aspect ratio so the widget
can place it inside a BoxFit.contain image.

Outer edge, deliberately. The outline is found by a radial scan from the
sticker's centre: for each angle, the farthest opaque pixel. That follows the
outside surface and skips the gaps between the tubes and the body, which is
what a tracker running round the picture should do -- it is a lap of the
sticker, not a tour of its holes.

Rerun after rerunning prepare_cycle_image.py; the outline is of that file.
"""
import math

from PIL import Image

SOURCE = 'assets/cycle_uterus.png'
OUT = 'lib/features/home/widgets/cycle_outline.dart'
SAMPLES = 240
WORK_WIDTH = 900  # scanned at this width; the outline does not need 4K


def outline(alpha):
    w, h = alpha.size
    px = alpha.load()

    # The centre of the opaque area, not of the box: the sticker's mass sits
    # above its middle, and a scan from the box centre clips the tubes.
    total = sx = sy = 0
    for y in range(0, h, 2):
        for x in range(0, w, 2):
            if px[x, y] > 128:
                total += 1
                sx += x
                sy += y
    cx, cy = sx / total, sy / total

    reach = math.hypot(w, h)
    points = []
    for i in range(SAMPLES):
        # Start at the top (-90 degrees) and go clockwise, as a clock does.
        angle = -math.pi / 2 + 2 * math.pi * i / SAMPLES
        dx, dy = math.cos(angle), math.sin(angle)
        far = None
        r = reach
        while r > 0:
            x, y = int(cx + dx * r), int(cy + dy * r)
            if 0 <= x < w and 0 <= y < h and px[x, y] > 128:
                far = (x, y)
                break
            r -= 1
        points.append(far if far else (cx, cy))

    # Smoothed a little, so the JPEG's edge noise does not become wobble in
    # a 12px stroke.
    smoothed = []
    n = len(points)
    for i in range(n):
        xs = [points[(i + k) % n][0] for k in (-2, -1, 0, 1, 2)]
        ys = [points[(i + k) % n][1] for k in (-2, -1, 0, 1, 2)]
        smoothed.append((sum(xs) / 5, sum(ys) / 5))

    return [(x / w, y / h) for x, y in smoothed]


def main():
    img = Image.open(SOURCE)
    w, h = img.size
    scale = WORK_WIDTH / w
    alpha = img.getchannel('A').resize(
        (WORK_WIDTH, round(h * scale)), Image.BILINEAR)
    points = outline(alpha)

    lines = [
        "import 'package:flutter/painting.dart';",
        '',
        '// Generated by tool/extract_cycle_outline.py from assets/cycle_uterus.png.',
        '// Do not edit by hand: rerun the tool after changing the image.',
        '',
        '/// Width over height of the sticker image.',
        'const double cycleOutlineAspect = %.6f;' % (w / h),
        '',
        "/// The sticker's outer edge, in image space (0..1), from the top clockwise.",
        'const List<Offset> cycleOutlinePoints = [',
    ]
    for x, y in points:
        lines.append('  Offset(%.4f, %.4f),' % (x, y))
    lines.append('];')
    lines.append('')

    with open(OUT, 'w', encoding='utf-8') as f:
        f.write('\n'.join(lines))
    print('wrote %s with %d points' % (OUT, len(points)))


if __name__ == '__main__':
    main()
