"""Reports what still needs translating, and writes the translator hand-off.

A key that a locale does not define inherits the English implementation, so the
app works and the string simply reads as untranslated. That makes the ARB files
themselves the work list: whatever is in `app_en.arb` and missing from
`app_hi.arb` is what a Hindi translator has left to do.

Run:
    python tool/translation_status.py            # summary
    python tool/translation_status.py --write    # also write TRANSLATION_TODO.md
"""
import argparse
import collections
import io
import json
import re
from pathlib import Path

ARB_DIR = Path('lib/l10n')

# Vocabulary a general translator should not be asked to guess at. These are
# condition names, symptoms and clinical measures; a wrong rendering here is a
# safety problem rather than an awkward phrase, so they are routed separately.
CLINICAL = re.compile(
    r'adenomyosis|endometriosis|pcos|pmdd|thyroid|ovulat|cervical|luteal'
    r'|follicular|menstrua|postpartum|perimenopaus|menopaus|contracepti'
    r'|basal body|hormon|discharge|fibroid|prolactin|estrogen|progesterone',
    re.I,
)


def load(path: Path) -> dict:
    return json.load(io.open(path, encoding='utf-8'),
                     object_pairs_hook=collections.OrderedDict)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--write', action='store_true')
    args = ap.parse_args()

    template = load(ARB_DIR / 'app_en.arb')
    keys = [k for k in template if not k.startswith('@')]

    locales = sorted(
        p for p in ARB_DIR.glob('app_*.arb') if not p.name.endswith('app_en.arb')
    )

    print(f'  English keys: {len(keys)}\n')
    print('  LOCALE  TRANSLATED  REMAINING')
    pending = {}
    for path in locales:
        code = path.stem.replace('app_', '')
        data = load(path)
        missing = [k for k in keys if k not in data]
        pending[code] = missing
        print(f'  {code:6}  {len(keys) - len(missing):10}  {len(missing):9}')

    clinical = [k for k in keys if CLINICAL.search(str(template[k]))]
    print(f'\n  of which clinical vocabulary: {len(clinical)}')
    print('  (route these to a clinician or medical translator, not a general one)')

    if not args.write:
        return

    # One file per locale would be tidier for a translation service, but a
    # single readable document is easier to hand to a person.
    out = ['# Translation to-do', '',
           'Generated by `tool/translation_status.py`. Do not edit by hand.', '',
           'A key missing from a locale falls back to English, so the app works '
           'while this list is worked through.', '']

    if clinical:
        out += ['## Clinical vocabulary — needs a medical translator', '',
                'Condition names, symptoms and clinical measures. A wrong '
                'rendering here is a safety problem, not an awkward phrase.', '',
                '| Key | English |', '|---|---|']
        for k in clinical:
            out.append(f'| `{k}` | {str(template[k]).replace("|", "\\|")} |')
        out.append('')

    ui_keys = [k for k in keys if k not in set(clinical)]
    out += ['## Interface copy', '',
            f'{len(ui_keys)} keys. Buttons, headings, messages and empty states.', '',
            '| Key | English |', '|---|---|']
    for k in ui_keys:
        out.append(f'| `{k}` | {str(template[k]).replace("|", "\\|")} |')

    Path('TRANSLATION_TODO.md').write_text('\n'.join(out) + '\n', encoding='utf-8')
    print('\n  wrote TRANSLATION_TODO.md')


if __name__ == '__main__':
    main()
