import { db } from '../utils/db.js';
import { logger } from '../utils/logger.js';

/**
 * The day's Discover feed, kept where every instance can see it.
 *
 * Discover is generated by an AI call capped at 16,000 output tokens -- by a
 * wide margin the most expensive request this backend makes -- and is meant to
 * be produced once per user per day. It was cached in a module-level `Map`,
 * which meant:
 *
 *   * every deploy, restart or sleep-wake threw the day's work away, and each
 *     active user paid for a fresh 16,000-token generation;
 *   * a second instance shared nothing with the first, so generations scaled
 *     with instance count rather than with users;
 *   * nothing ever evicted a key, so the map grew for the life of the process.
 *
 * Stored in Mongo instead: it survives restarts, is shared across instances,
 * and expires on its own.
 */

const COLLECTION = 'discover_daily_cache';

/** How long a cached day survives. */
export const DISCOVER_CACHE_TTL_SECONDS = 48 * 60 * 60;

function cleanUserId(userId) {
  return typeof userId === 'string' ? userId.replace(/^user:/, '') : userId;
}

/**
 * The stored feed for this key, or null.
 *
 * Never throws: a cache miss and an unreachable database must both fall
 * through to generation rather than fail the request.
 */
export async function getCachedDiscover(cacheKey) {
  if (!cacheKey) return null;

  try {
    const row = await db.collection(COLLECTION).findOne({ cache_key: cacheKey });
    return row?.payload ?? null;
  } catch (error) {
    logger.warn(`Discover cache read failed for ${cacheKey}: ${error.message}`);
    return null;
  }
}

/**
 * Stores the feed for this key.
 *
 * Upserts, so two requests racing to generate the same day converge on one row
 * instead of duplicating. Never throws: failing to cache is a cost problem, not
 * a reason to lose a response the user is waiting for.
 */
export async function saveCachedDiscover({ cacheKey, userId, dateStr, payload }) {
  if (!cacheKey || !payload) return;

  try {
    await db.collection(COLLECTION).updateOne(
      { cache_key: cacheKey },
      {
        $set: {
          cache_key: cacheKey,
          user_id: cleanUserId(userId) ?? null,
          date_str: dateStr ?? null,
          payload,
          created_at: new Date(),
        },
      },
      { upsert: true },
    );
  } catch (error) {
    logger.warn(`Discover cache write failed for ${cacheKey}: ${error.message}`);
  }
}
