/**
 * Deterministic pregnancy arithmetic (spec §15, and §26 "AI MUST NOT BE
 * RESPONSIBLE FOR ... Pregnancy week arithmetic").
 *
 * Pure module. Week and trimester are derived from a stored source date, never
 * generated by AI. Milestone copy IDs point at the medical content service so
 * the words themselves stay clinically reviewed.
 */

export const PREGNANCY_CALC_VERSION = 'pregnancy-v1.0.0';

const MS_PER_DAY = 86400000;
const TERM_DAYS = 280; // Naegele: 40 weeks from LMP

function parseDate(value) {
  if (!value) return null;
  if (value instanceof Date) {
    return Number.isNaN(value.getTime())
      ? null
      : new Date(Date.UTC(value.getUTCFullYear(), value.getUTCMonth(), value.getUTCDate()));
  }
  const match = /^(\d{4})-(\d{2})-(\d{2})/.exec(String(value).trim());
  if (!match) return null;
  const d = new Date(Date.UTC(Number(match[1]), Number(match[2]) - 1, Number(match[3])));
  return Number.isNaN(d.getTime()) ? null : d;
}

function isoDate(d) {
  if (!d) return null;
  return `${d.getUTCFullYear()}-${String(d.getUTCMonth() + 1).padStart(2, '0')}-${String(d.getUTCDate()).padStart(2, '0')}`;
}

function addDays(d, days) {
  return new Date(d.getTime() + days * MS_PER_DAY);
}

function daysBetween(a, b) {
  return Math.round((b.getTime() - a.getTime()) / MS_PER_DAY);
}

export function trimesterForWeek(week) {
  if (week === null || week === undefined) return null;
  if (week < 13) return 1;
  if (week < 27) return 2;
  return 3;
}

/**
 * Calculates pregnancy state from whichever source date the user gave.
 *
 * Accepts { dueDate, lmpDate, week, weekRecordedOn } and a reference date.
 * Returns an explicit `state` of `ready` or `insufficient_data` - the spec
 * forbids fake precision when the dates are unknown.
 */
export function calculatePregnancyState({ dueDate, lmpDate, week, weekRecordedOn, referenceDate } = {}) {
  const today = parseDate(referenceDate) ?? parseDate(new Date());
  const due = parseDate(dueDate);
  const lmp = parseDate(lmpDate);

  let estimatedDueDate = due;
  let dateSource = due ? 'due_date' : null;

  if (!estimatedDueDate && lmp) {
    estimatedDueDate = addDays(lmp, TERM_DAYS);
    dateSource = 'lmp';
  }

  if (!estimatedDueDate && Number.isFinite(Number(week))) {
    // Reconstruct the due date from a self-reported week at the date it was
    // reported, so the week keeps advancing on its own afterwards.
    const anchor = parseDate(weekRecordedOn) ?? today;
    const gestationalDaysAtAnchor = Math.round(Number(week) * 7);
    estimatedDueDate = addDays(anchor, TERM_DAYS - gestationalDaysAtAnchor);
    dateSource = 'reported_week';
  }

  if (!estimatedDueDate) {
    return {
      state: 'insufficient_data',
      calculationVersion: PREGNANCY_CALC_VERSION,
      reason: 'no_source_date',
      message: 'Add a due date, last period date or current week to see your pregnancy timeline.',
      dueDate: null,
      gestationalWeek: null,
      gestationalDay: null,
      trimester: null,
      daysRemaining: null,
      isPastDue: false,
      isTerm: false,
      dateSource: null,
      referenceDate: isoDate(today),
    };
  }

  const conceptionAnchor = addDays(estimatedDueDate, -TERM_DAYS); // gestational day 0
  const gestationalDays = daysBetween(conceptionAnchor, today);

  if (gestationalDays < 0) {
    return {
      state: 'insufficient_data',
      calculationVersion: PREGNANCY_CALC_VERSION,
      reason: 'due_date_out_of_range',
      message: 'That due date is more than 40 weeks away. Please check the date.',
      dueDate: isoDate(estimatedDueDate),
      gestationalWeek: null,
      gestationalDay: null,
      trimester: null,
      daysRemaining: daysBetween(today, estimatedDueDate),
      isPastDue: false,
      isTerm: false,
      dateSource,
      referenceDate: isoDate(today),
    };
  }

  const gestationalWeek = Math.floor(gestationalDays / 7);
  const gestationalDay = gestationalDays % 7;
  const daysRemaining = daysBetween(today, estimatedDueDate);

  return {
    state: 'ready',
    calculationVersion: PREGNANCY_CALC_VERSION,
    reason: null,
    message: null,
    dueDate: isoDate(estimatedDueDate),
    lmpDate: lmp ? isoDate(lmp) : isoDate(conceptionAnchor),
    gestationalWeek,
    gestationalDay,
    gestationalDays,
    displayWeek: `${gestationalWeek}w ${gestationalDay}d`,
    trimester: trimesterForWeek(gestationalWeek),
    daysRemaining,
    isPastDue: daysRemaining < 0,
    isTerm: gestationalWeek >= 37,
    isViable: gestationalWeek >= 24,
    dateSource,
    referenceDate: isoDate(today),
  };
}

/**
 * Milestone schedule. `contentId` resolves against the medical content service
 * so the displayed body text is always sourced, reviewed and versioned - the
 * schedule here only decides *when* a milestone becomes relevant.
 */
export const PREGNANCY_MILESTONES = Object.freeze([
  { id: 'pg_wk04', week: 4, title: 'Pregnancy confirmed', category: 'milestone', contentId: 'mc_pregnancy_week_04' },
  { id: 'pg_wk06', week: 6, title: 'First prenatal appointment window opens', category: 'appointment', contentId: 'mc_pregnancy_week_06' },
  { id: 'pg_wk08', week: 8, title: 'Early pregnancy changes', category: 'education', contentId: 'mc_pregnancy_week_08' },
  { id: 'pg_wk12', week: 12, title: 'End of first trimester', category: 'milestone', contentId: 'mc_pregnancy_week_12' },
  { id: 'pg_wk16', week: 16, title: 'Second trimester begins', category: 'milestone', contentId: 'mc_pregnancy_week_16' },
  { id: 'pg_wk20', week: 20, title: 'Anatomy scan window', category: 'appointment', contentId: 'mc_pregnancy_week_20' },
  { id: 'pg_wk24', week: 24, title: 'Glucose screening window', category: 'appointment', contentId: 'mc_pregnancy_week_24' },
  { id: 'pg_wk28', week: 28, title: 'Third trimester begins', category: 'milestone', contentId: 'mc_pregnancy_week_28' },
  { id: 'pg_wk32', week: 32, title: 'Growth check window', category: 'appointment', contentId: 'mc_pregnancy_week_32' },
  { id: 'pg_wk36', week: 36, title: 'Preparing for birth', category: 'education', contentId: 'mc_pregnancy_week_36' },
  { id: 'pg_wk37', week: 37, title: 'Full term', category: 'milestone', contentId: 'mc_pregnancy_week_37' },
  { id: 'pg_wk40', week: 40, title: 'Due date', category: 'milestone', contentId: 'mc_pregnancy_week_40' },
]);

/**
 * Returns milestones split into passed / current / upcoming for the given week.
 * Returns an empty structure rather than fabricating one when the week is
 * unknown.
 */
export function getMilestones(gestationalWeek) {
  if (gestationalWeek === null || gestationalWeek === undefined) {
    return { passed: [], current: null, upcoming: [], state: 'insufficient_data' };
  }

  const passed = [];
  const upcoming = [];
  let current = null;

  for (const milestone of PREGNANCY_MILESTONES) {
    if (milestone.week < gestationalWeek) {
      passed.push(milestone);
    } else if (milestone.week === gestationalWeek) {
      current = milestone;
    } else {
      upcoming.push(milestone);
    }
  }

  if (!current && passed.length > 0) {
    current = passed[passed.length - 1];
  }

  return { passed, current, upcoming: upcoming.slice(0, 3), state: 'ready' };
}

/**
 * Pregnancy exit outcomes. `blocksPregnancyContent` is what stops week-by-week
 * content from continuing afterwards (spec §15).
 */
export const PREGNANCY_END_OUTCOMES = Object.freeze({
  birth: { nextStage: 'postpartum', blocksPregnancyContent: true, requiresConfirmation: true, supportFlow: 'postpartum_welcome' },
  loss: { nextStage: 'everyday_wellness', blocksPregnancyContent: true, requiresConfirmation: true, supportFlow: 'pregnancy_loss_support' },
  termination: { nextStage: 'everyday_wellness', blocksPregnancyContent: true, requiresConfirmation: true, supportFlow: 'pregnancy_loss_support' },
  other: { nextStage: 'everyday_wellness', blocksPregnancyContent: true, requiresConfirmation: true, supportFlow: 'general_support' },
  prefer_not_to_say: { nextStage: 'everyday_wellness', blocksPregnancyContent: true, requiresConfirmation: true, supportFlow: 'general_support' },
});

export function resolvePregnancyEnd(outcome) {
  return PREGNANCY_END_OUTCOMES[outcome] ?? null;
}
