import 'dart:async';
import 'dart:convert';
import 'dart:math' as math;

import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;

import 'api_auth_service.dart';
import 'api_base_url.dart';
import 'auth_storage.dart';

/// The states the backend can return for any card (spec section 27
/// "STANDARD API RESPONSE CONTRACT" and section 4 "FRONTEND STATES EVERY CARD
/// MUST SUPPORT").
///
/// `loading`, `stale` and `offline` are client-side states: the server never
/// sends them, but every card has to be able to render them.
enum ApiState {
  loading,
  ready,
  empty,
  insufficientData,
  restricted,
  error,
  stale,
  offline,
}

ApiState _parseState(String? raw) {
  switch (raw) {
    case 'ready':
      return ApiState.ready;
    case 'empty':
      return ApiState.empty;
    case 'insufficient_data':
    case 'not_enough_data':
      return ApiState.insufficientData;
    case 'restricted':
      return ApiState.restricted;
    case 'error':
      return ApiState.error;
    default:
      return ApiState.error;
  }
}

/// A typed wrapper around one backend response.
///
/// Carries the full contract so a widget can decide what to render without
/// guessing: `state` says which of the eight card states applies, `source`
/// says whether the value was reported by the user, calculated by a rule, or
/// generated by AI, and `version` identifies the calculation behind a number.
@immutable
class ApiResult<T> {
  final T? data;
  final ApiState state;
  final DateTime? lastUpdated;
  final String? source;
  final String? version;
  final Map<String, dynamic>? permissions;
  final String? errorCode;
  final String? errorMessage;
  final Map<String, dynamic>? meta;

  const ApiResult({
    this.data,
    required this.state,
    this.lastUpdated,
    this.source,
    this.version,
    this.permissions,
    this.errorCode,
    this.errorMessage,
    this.meta,
  });

  const ApiResult.loading()
      : data = null,
        state = ApiState.loading,
        lastUpdated = null,
        source = null,
        version = null,
        permissions = null,
        errorCode = null,
        errorMessage = null,
        meta = null;

  const ApiResult.offline({this.data, this.lastUpdated})
      : state = ApiState.offline,
        source = null,
        version = null,
        permissions = null,
        errorCode = 'OFFLINE',
        errorMessage = null,
        meta = null;

  bool get isReady => state == ApiState.ready;
  bool get hasData => data != null && state == ApiState.ready;

  /// True when the card should show a "not enough data yet" treatment rather
  /// than an empty one. The spec keeps these distinct on purpose.
  bool get isInsufficientData => state == ApiState.insufficientData;

  /// True when the information exists but the viewer is not permitted to see
  /// it. Partner surfaces use this to render the restricted treatment.
  bool get isRestricted => state == ApiState.restricted;

  bool get isError => state == ApiState.error;

  /// True when a displayed value came from AI rather than from the user's own
  /// logs or a deterministic rule, so the UI can label it.
  bool get isAiGenerated => source == 'ai';

  ApiResult<R> map<R>(R Function(T value) transform) {
    return ApiResult<R>(
      data: data == null ? null : transform(data as T),
      state: state,
      lastUpdated: lastUpdated,
      source: source,
      version: version,
      permissions: permissions,
      errorCode: errorCode,
      errorMessage: errorMessage,
      meta: meta,
    );
  }
}

/// Shared HTTP client for the spec-aligned `/api/v1` surface.
///
/// One place owns the base URL, the auth header, timeouts, the response
/// contract and error mapping, so every screen behaves the same way.
class ApiContractClient {
  ApiContractClient._();

  static const Duration _timeout = Duration(seconds: 20);

  /// A timed-out request is retried once, with longer to answer.
  ///
  /// The API is deployed on an instance that spins down when idle, so the
  /// first request after a quiet spell waits on a cold start. Measured against
  /// the live host: a first call hung past 90s and the next answered in 18.3s,
  /// while a warm one comes back in about 1s. Every screen that happened to
  /// make that first call reported a request timeout -- on the home page, that
  /// is Docsy insights and cycle patterns.
  ///
  /// The retry is what actually fixes it: the failed attempt is what wakes the
  /// instance, so the second usually succeeds. A raised timeout alone would
  /// only mean waiting longer before showing the same error.
  static const Duration _wakeTimeout = Duration(seconds: 45);

  static String get _base => '${resolveApiBaseUrl()}/api/v1';

  static Map<String, String> _headers({String? idempotencyKey}) {
    final token = AuthStorage.getToken();
    return {
      'Content-Type': 'application/json',
      if (token != null) 'Authorization': 'Bearer $token',
      'Idempotency-Key': ?idempotencyKey,
    };
  }

  /// Guards against a refresh storm: a 401 on the refresh call itself, or
  /// several requests failing at once, must not each start their own refresh.
  static bool _refreshing = false;

  static Future<bool> _tryRefreshSession() async {
    if (_refreshing) return false;
    _refreshing = true;
    try {
      return await ApiAuthService().refreshSession();
    } catch (_) {
      return false;
    } finally {
      _refreshing = false;
    }
  }

  /// Whether repeating this exact request is safe.
  ///
  /// A retry is only ever correct when sending the request twice leaves the
  /// same result as sending it once. `GET` and `PUT` satisfy that by
  /// definition. `POST` does not — it creates something — so it qualifies only
  /// when it carries an idempotency key the server actually dedupes on, which
  /// today is the events and period-log routes. `PATCH` may be a partial or
  /// relative change, and a repeated `DELETE` reports a 404 for work that
  /// succeeded, so neither is retried.
  ///
  /// Without this, a slow `POST /posts` that the server had already accepted
  /// was sent again and published the post twice.
  static bool _isRepeatable(String method, {String? idempotencyKey}) {
    switch (method) {
      case 'GET':
      case 'PUT':
        return true;
      case 'POST':
        return idempotencyKey != null && idempotencyKey.isNotEmpty;
      default:
        return false;
    }
  }

  /// How long the server asked us to wait, bounded.
  ///
  /// `Retry-After` is seconds here. It is clamped because a caller must not be
  /// left waiting on a number the app did not choose, and jittered because
  /// every client saturated at the same moment would otherwise come back at the
  /// same moment and saturate it again.
  static Duration _retryAfterDelay(http.Response response) {
    final header = response.headers['retry-after'];
    final seconds = int.tryParse(header?.trim() ?? '') ?? 2;
    // .toInt() because num.clamp returns num, which Duration will not take.
    final int bounded = seconds.clamp(1, 10).toInt();
    final int jitterMs = _random.nextInt(400);
    return Duration(milliseconds: bounded * 1000 + jitterMs);
  }

  static final math.Random _random = math.Random();

  static Future<ApiResult<T>> _send<T>(
    Future<http.Response> Function() request,
    T Function(dynamic data)? parse, {
    required bool repeatable,
  }) async {
    try {
      http.Response response;
      try {
        response = await request().timeout(_timeout);
      } on TimeoutException {
        // The instance sleeps when idle, and the first request after that waits
        // on a cold start. The failed attempt is what wakes it, so a second one
        // usually succeeds -- but only where repeating it is safe. A timed-out
        // write that the server had in fact accepted must not be sent again.
        if (!repeatable) rethrow;
        response = await request().timeout(_wakeTimeout);
      }

      // An expired access token is recoverable: the refresh token was being
      // stored and never used, so a session that lapsed mid-use turned every
      // request into an error. One retry, and only after a refresh actually
      // succeeds, so a genuinely revoked session still surfaces as 401.
      if (response.statusCode == 401 && !_refreshing) {
        if (await _tryRefreshSession()) {
          response = await request().timeout(_timeout);
        }
      }

      // 503 means every database connection is in use: the service is busy, not
      // broken, and the same request will succeed shortly. Waiting the interval
      // it asked for turns that into content rather than an error message --
      // again only where repeating is safe.
      if (response.statusCode == 503 && repeatable) {
        await Future<void>.delayed(_retryAfterDelay(response));
        response = await request().timeout(_wakeTimeout);
      }

      return _decode<T>(response, parse);
    } on TimeoutException {
      return const ApiResult(
        state: ApiState.error,
        errorCode: 'TIMEOUT',
        errorMessage: 'The request timed out. Please try again.',
      );
    } catch (error) {
      // A failed request is treated as offline rather than an error, so cards
      // can show the last known safe state and queue supported writes
      // (spec section 25).
      if (kDebugMode) {
        // The host is worth printing: the usual cause of this branch in
        // development is a base URL the device cannot route to, which is not
        // a connectivity problem and cannot be diagnosed from the UI copy.
        debugPrint('[api] request to ${resolveApiBaseUrl()} failed: $error');
      }
      return const ApiResult(
        state: ApiState.offline,
        errorCode: 'NETWORK_UNAVAILABLE',
        errorMessage: 'Could not reach the server. Showing the last known state.',
      );
    }
  }

  static ApiResult<T> _decode<T>(http.Response response, T Function(dynamic data)? parse) {
    Map<String, dynamic> body;
    try {
      final decoded = jsonDecode(response.body);
      body = decoded is Map<String, dynamic> ? decoded : <String, dynamic>{};
    } catch (_) {
      return ApiResult<T>(
        state: ApiState.error,
        errorCode: 'MALFORMED_RESPONSE',
        errorMessage: 'The server returned an unexpected response.',
      );
    }

    // Routes outside the v1 surface still use the older error shape.
    if (!body.containsKey('state') && body.containsKey('error')) {
      final error = body['error'];
      return ApiResult<T>(
        state: ApiState.error,
        errorCode: error is Map ? error['code']?.toString() : null,
        errorMessage: error is Map ? error['message']?.toString() : error?.toString(),
      );
    }

    final state = _parseState(body['state']?.toString());
    final rawData = body['data'];

    // A refusal carries its reasons in `data` -- which stage she is in, whether
    // a confirmation would do, what context is missing -- and no payload of
    // the requested type. Parsing it as one lost every reason, so a refused
    // stage change read as "could not be saved" whatever the server said.
    if (state == ApiState.error) {
      return ApiResult<T>(
        state: ApiState.error,
        errorCode: body['errorCode']?.toString(),
        errorMessage: body['error'] is Map ? (body['error'] as Map)['message']?.toString() : null,
        meta: body['meta'] is Map<String, dynamic>
            ? body['meta'] as Map<String, dynamic>
            : (rawData is Map ? Map<String, dynamic>.from(rawData) : null),
      );
    }

    T? parsed;
    if (rawData != null && parse != null) {
      try {
        parsed = parse(rawData);
      } catch (error) {
        if (kDebugMode) {
          debugPrint('[api] failed to parse payload: $error');
        }
        return ApiResult<T>(
          state: ApiState.error,
          errorCode: 'PARSE_FAILED',
          errorMessage: 'The response could not be read.',
        );
      }
    } else if (rawData is T) {
      parsed = rawData;
    }

    return ApiResult<T>(
      data: parsed,
      state: state,
      lastUpdated: body['lastUpdated'] != null ? DateTime.tryParse(body['lastUpdated'].toString()) : null,
      source: body['source']?.toString(),
      version: body['version']?.toString(),
      permissions: body['permissions'] is Map<String, dynamic> ? body['permissions'] as Map<String, dynamic> : null,
      errorCode: body['errorCode']?.toString(),
      errorMessage: body['error'] is Map ? (body['error'] as Map)['message']?.toString() : null,
      meta: body['meta'] is Map<String, dynamic> ? body['meta'] as Map<String, dynamic> : null,
    );
  }

  /// A client to send with instead of the package's top-level functions;
  /// tests hand in a MockClient. Null in the app.
  static http.Client? clientOverride;

  static http.Client get _http => clientOverride ?? http.Client();

  static Future<ApiResult<T>> get<T>(
    String path, {
    Map<String, String>? query,
    T Function(dynamic data)? parse,
  }) {
    final uri = Uri.parse('$_base$path').replace(
      queryParameters: query == null || query.isEmpty ? null : query,
    );
    return _send<T>(() => _http.get(uri, headers: _headers()), parse,
        repeatable: _isRepeatable('GET'));
  }

  static Future<ApiResult<T>> post<T>(
    String path, {
    Object? body,
    String? idempotencyKey,
    T Function(dynamic data)? parse,
  }) {
    return _send<T>(
      () => _http.post(
        Uri.parse('$_base$path'),
        headers: _headers(idempotencyKey: idempotencyKey),
        body: body == null ? null : jsonEncode(body),
      ),
      parse,
      repeatable: _isRepeatable('POST', idempotencyKey: idempotencyKey),
    );
  }

  static Future<ApiResult<T>> put<T>(
    String path, {
    Object? body,
    T Function(dynamic data)? parse,
  }) {
    return _send<T>(
      () => _http.put(
        Uri.parse('$_base$path'),
        headers: _headers(),
        body: body == null ? null : jsonEncode(body),
      ),
      parse,
      repeatable: _isRepeatable('PUT'),
    );
  }

  static Future<ApiResult<T>> patch<T>(
    String path, {
    Object? body,
    T Function(dynamic data)? parse,
  }) {
    return _send<T>(
      () => _http.patch(
        Uri.parse('$_base$path'),
        headers: _headers(),
        body: body == null ? null : jsonEncode(body),
      ),
      parse,
      repeatable: _isRepeatable('PATCH'),
    );
  }

  static Future<ApiResult<T>> delete<T>(
    String path, {
    Map<String, String>? query,
    Object? body,
    T Function(dynamic data)? parse,
  }) {
    final uri = Uri.parse('$_base$path').replace(
      queryParameters: query == null || query.isEmpty ? null : query,
    );
    return _send<T>(
      () => _http.delete(
        uri,
        headers: _headers(),
        body: body == null ? null : jsonEncode(body),
      ),
      parse,
      repeatable: _isRepeatable('DELETE'),
    );
  }
}

/// Helpers shared by the typed models below.
class ApiParse {
  static List<Map<String, dynamic>> list(dynamic value) {
    if (value is! List) return const [];
    return value.whereType<Map>().map((e) => Map<String, dynamic>.from(e)).toList();
  }

  static Map<String, dynamic> map(dynamic value) {
    if (value is Map) return Map<String, dynamic>.from(value);
    return const {};
  }

  static DateTime? date(dynamic value) {
    if (value == null) return null;
    return DateTime.tryParse(value.toString());
  }

  static String dateOnly(DateTime value) {
    return '${value.year.toString().padLeft(4, '0')}-'
        '${value.month.toString().padLeft(2, '0')}-'
        '${value.day.toString().padLeft(2, '0')}';
  }

  static int? intOrNull(dynamic value) {
    if (value == null) return null;
    if (value is int) return value;
    return int.tryParse(value.toString());
  }

  static double? doubleOrNull(dynamic value) {
    if (value == null) return null;
    if (value is num) return value.toDouble();
    return double.tryParse(value.toString());
  }
}
